set(_CATKIN_CURRENT_PACKAGE "rqt_gui")
set(rqt_gui_VERSION "0.2.14")
set(rqt_gui_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rqt_gui_PACKAGE_FORMAT "1")
set(rqt_gui_BUILD_DEPENDS "qt_gui")
set(rqt_gui_BUILD_EXPORT_DEPENDS "catkin" "qt_gui")
set(rqt_gui_BUILD_EXPORT_DEPENDS_qt_gui_VERSION_GTE "0.2.18")
set(rqt_gui_BUILDTOOL_DEPENDS "catkin")
set(rqt_gui_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_gui_EXEC_DEPENDS "catkin" "qt_gui")
set(rqt_gui_EXEC_DEPENDS_qt_gui_VERSION_GTE "0.2.18")
set(rqt_gui_RUN_DEPENDS "catkin" "qt_gui")
set(rqt_gui_RUN_DEPENDS_qt_gui_VERSION_GTE "0.2.18")
set(rqt_gui_TEST_DEPENDS )
set(rqt_gui_DOC_DEPENDS )
set(rqt_gui_DEPRECATED "")