set(rqt_gui_SETUP_PY_VERSION "0.2.14")
set(rqt_gui_SETUP_PY_SCRIPTS "bin/rqt")
set(rqt_gui_SETUP_PY_PACKAGES "rqt_gui")
set(rqt_gui_SETUP_PY_PACKAGE_DIRS "src/rqt_gui")
set(rqt_gui_SETUP_PY_MODULES "")
set(rqt_gui_SETUP_PY_MODULE_DIRS "")