set(_CATKIN_CURRENT_PACKAGE "rosconsole_bridge")
set(rosconsole_bridge_VERSION "0.4.4")
set(rosconsole_bridge_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>, Ioan Sucan <isucan@gmail.com>")
set(rosconsole_bridge_PACKAGE_FORMAT "1")
set(rosconsole_bridge_BUILD_DEPENDS "libconsole-bridge-dev" "rosconsole")
set(rosconsole_bridge_BUILD_DEPENDS_rosconsole_VERSION_GTE "1.11.5")
set(rosconsole_bridge_BUILD_EXPORT_DEPENDS "libconsole-bridge-dev" "rosconsole")
set(rosconsole_bridge_BUILDTOOL_DEPENDS "catkin")
set(rosconsole_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(rosconsole_bridge_EXEC_DEPENDS "libconsole-bridge-dev" "rosconsole")
set(rosconsole_bridge_RUN_DEPENDS "libconsole-bridge-dev" "rosconsole")
set(rosconsole_bridge_TEST_DEPENDS )
set(rosconsole_bridge_DOC_DEPENDS )
set(rosconsole_bridge_DEPRECATED "")