/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.17
 */

#include "sipAPIlibqt_gui_cpp_sip.h"

#line 115 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 12 "/opt/ros_catkin_ws/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipQList0101qt_gui_cppPluginDescriptor.cpp"

#line 7 "plugin_descriptor.sip"
#include <qt_gui_cpp/plugin_descriptor.h>
#line 16 "/opt/ros_catkin_ws/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipQList0101qt_gui_cppPluginDescriptor.cpp"


extern "C" {static void assign_QList_0101qt_gui_cpp_PluginDescriptor(void *, SIP_SSIZE_T, const void *);}
static void assign_QList_0101qt_gui_cpp_PluginDescriptor(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QList<qt_gui_cpp::PluginDescriptor*> *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QList<qt_gui_cpp::PluginDescriptor*> *>(sipSrc);
}


extern "C" {static void *array_QList_0101qt_gui_cpp_PluginDescriptor(SIP_SSIZE_T);}
static void *array_QList_0101qt_gui_cpp_PluginDescriptor(SIP_SSIZE_T sipNrElem)
{
    return new QList<qt_gui_cpp::PluginDescriptor*>[sipNrElem];
}


extern "C" {static void *copy_QList_0101qt_gui_cpp_PluginDescriptor(const void *, SIP_SSIZE_T);}
static void *copy_QList_0101qt_gui_cpp_PluginDescriptor(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QList<qt_gui_cpp::PluginDescriptor*>(reinterpret_cast<const QList<qt_gui_cpp::PluginDescriptor*> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_QList_0101qt_gui_cpp_PluginDescriptor(void *, int);}
static void release_QList_0101qt_gui_cpp_PluginDescriptor(void *ptr, int)
{
    Py_BEGIN_ALLOW_THREADS
    delete reinterpret_cast<QList<qt_gui_cpp::PluginDescriptor*> *>(ptr);
    Py_END_ALLOW_THREADS
}



extern "C" {static int convertTo_QList_0101qt_gui_cpp_PluginDescriptor(PyObject *, void **, int *, PyObject *);}
static int convertTo_QList_0101qt_gui_cpp_PluginDescriptor(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QList<qt_gui_cpp::PluginDescriptor*> **sipCppPtr = reinterpret_cast<QList<qt_gui_cpp::PluginDescriptor*> **>(sipCppPtrV);

#line 145 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
    SIP_SSIZE_T len;

    // Check the type if that is all that is required.
    if (sipIsErr == NULL)
    {
        if (!PySequence_Check(sipPy) || (len = PySequence_Size(sipPy)) < 0)
            return 0;

        for (SIP_SSIZE_T i = 0; i < len; ++i)
        {
            PyObject *itm = PySequence_ITEM(sipPy, i);
            bool ok = (itm && sipCanConvertToType(itm, sipType_qt_gui_cpp_PluginDescriptor, 0));

            Py_XDECREF(itm);

            if (!ok)
                return 0;
        }

        return 1;
    }

    QList<qt_gui_cpp::PluginDescriptor *> *ql = new QList<qt_gui_cpp::PluginDescriptor *>;
    len = PySequence_Size(sipPy);
 
    for (SIP_SSIZE_T i = 0; i < len; ++i)
    {
        PyObject *itm = PySequence_ITEM(sipPy, i);
        qt_gui_cpp::PluginDescriptor *t = reinterpret_cast<qt_gui_cpp::PluginDescriptor *>(sipConvertToType(itm, sipType_qt_gui_cpp_PluginDescriptor, sipTransferObj, 0, 0, sipIsErr));

        Py_DECREF(itm);
 
        if (*sipIsErr)
        {
            delete ql;
            return 0;
        }

        ql->append(t);
    }
 
    *sipCppPtr = ql;
 
    return sipGetState(sipTransferObj);
#line 101 "/opt/ros_catkin_ws/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipQList0101qt_gui_cppPluginDescriptor.cpp"
}


extern "C" {static PyObject *convertFrom_QList_0101qt_gui_cpp_PluginDescriptor(void *, PyObject *);}
static PyObject *convertFrom_QList_0101qt_gui_cpp_PluginDescriptor(void *sipCppV, PyObject *sipTransferObj)
{
   QList<qt_gui_cpp::PluginDescriptor*> *sipCpp = reinterpret_cast<QList<qt_gui_cpp::PluginDescriptor*> *>(sipCppV);

#line 119 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
    // Create the list.
    PyObject *l;

    if ((l = PyList_New(sipCpp->size())) == NULL)
        return NULL;

    // Set the list elements.
    for (int i = 0; i < sipCpp->size(); ++i)
    {
        qt_gui_cpp::PluginDescriptor *t = sipCpp->at(i);
        PyObject *tobj;

        // The explicit (void *) cast allows qt_gui_cpp::PluginDescriptor to be const.
        if ((tobj = sipConvertFromType((void *)t, sipType_qt_gui_cpp_PluginDescriptor, sipTransferObj)) == NULL)
        {
            Py_DECREF(l);
            return NULL;
        }

        PyList_SET_ITEM(l, i, tobj);
    }

    return l;
#line 134 "/opt/ros_catkin_ws/build_isolated/qt_gui_cpp/sip/qt_gui_cpp_sip/siplibqt_gui_cpp_sipQList0101qt_gui_cppPluginDescriptor.cpp"
}


sipMappedTypeDef sipTypeDef_libqt_gui_cpp_sip_QList_0101qt_gui_cpp_PluginDescriptor = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_108,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_QList_0101qt_gui_cpp_PluginDescriptor,
    array_QList_0101qt_gui_cpp_PluginDescriptor,
    copy_QList_0101qt_gui_cpp_PluginDescriptor,
    release_QList_0101qt_gui_cpp_PluginDescriptor,
    convertTo_QList_0101qt_gui_cpp_PluginDescriptor,
    convertFrom_QList_0101qt_gui_cpp_PluginDescriptor
};
