set(_CATKIN_CURRENT_PACKAGE "rqt_web")
set(rqt_web_VERSION "0.3.13")
set(rqt_web_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_web_PACKAGE_FORMAT "1")
set(rqt_web_BUILD_DEPENDS )
set(rqt_web_BUILD_EXPORT_DEPENDS "python-rospkg" "qt_gui" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_web_BUILDTOOL_DEPENDS "catkin")
set(rqt_web_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_web_EXEC_DEPENDS "python-rospkg" "qt_gui" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_web_RUN_DEPENDS "python-rospkg" "qt_gui" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_web_TEST_DEPENDS )
set(rqt_web_DOC_DEPENDS )
set(rqt_web_DEPRECATED "")