set(_CATKIN_CURRENT_PACKAGE "rqt_gui_cpp")
set(rqt_gui_cpp_VERSION "0.2.14")
set(rqt_gui_cpp_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rqt_gui_cpp_PACKAGE_FORMAT "1")
set(rqt_gui_cpp_BUILD_DEPENDS "qt_gui" "qt_gui_cpp" "roscpp" "nodelet")
set(rqt_gui_cpp_BUILD_DEPENDS_qt_gui_VERSION_GTE "0.2.22")
set(rqt_gui_cpp_BUILD_DEPENDS_qt_gui_cpp_VERSION_GTE "0.2.22")
set(rqt_gui_cpp_BUILD_EXPORT_DEPENDS "qt_gui" "qt_gui_cpp" "roscpp" "nodelet")
set(rqt_gui_cpp_BUILD_EXPORT_DEPENDS_qt_gui_VERSION_GTE "0.2.22")
set(rqt_gui_cpp_BUILD_EXPORT_DEPENDS_qt_gui_cpp_VERSION_GTE "0.2.22")
set(rqt_gui_cpp_BUILDTOOL_DEPENDS "catkin")
set(rqt_gui_cpp_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_gui_cpp_EXEC_DEPENDS "qt_gui" "qt_gui_cpp" "roscpp" "nodelet")
set(rqt_gui_cpp_EXEC_DEPENDS_qt_gui_VERSION_GTE "0.2.22")
set(rqt_gui_cpp_EXEC_DEPENDS_qt_gui_cpp_VERSION_GTE "0.2.22")
set(rqt_gui_cpp_RUN_DEPENDS "qt_gui" "qt_gui_cpp" "roscpp" "nodelet")
set(rqt_gui_cpp_RUN_DEPENDS_qt_gui_VERSION_GTE "0.2.22")
set(rqt_gui_cpp_RUN_DEPENDS_qt_gui_cpp_VERSION_GTE "0.2.22")
set(rqt_gui_cpp_TEST_DEPENDS )
set(rqt_gui_cpp_DOC_DEPENDS )
set(rqt_gui_cpp_DEPRECATED "")