set(_CATKIN_CURRENT_PACKAGE "rosgraph_msgs")
set(rosgraph_msgs_VERSION "1.11.2")
set(rosgraph_msgs_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosgraph_msgs_PACKAGE_FORMAT "1")
set(rosgraph_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(rosgraph_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs")
set(rosgraph_msgs_BUILDTOOL_DEPENDS "catkin")
set(rosgraph_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(rosgraph_msgs_EXEC_DEPENDS "message_runtime" "std_msgs")
set(rosgraph_msgs_RUN_DEPENDS "message_runtime" "std_msgs")
set(rosgraph_msgs_TEST_DEPENDS )
set(rosgraph_msgs_DOC_DEPENDS )
set(rosgraph_msgs_DEPRECATED "")