set(_CATKIN_CURRENT_PACKAGE "rqt_bag_plugins")
set(rqt_bag_plugins_VERSION "0.3.13")
set(rqt_bag_plugins_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>, Austin Hendrix <namniart@gmail.com>")
set(rqt_bag_plugins_PACKAGE_FORMAT "1")
set(rqt_bag_plugins_BUILD_DEPENDS )
set(rqt_bag_plugins_BUILD_EXPORT_DEPENDS "geometry_msgs" "python-cairo" "python-imaging" "rosbag" "roslib" "rospy" "rqt_bag" "rqt_gui" "rqt_gui_py" "rqt_plot" "sensor_msgs" "std_msgs")
set(rqt_bag_plugins_BUILDTOOL_DEPENDS "catkin")
set(rqt_bag_plugins_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_bag_plugins_EXEC_DEPENDS "geometry_msgs" "python-cairo" "python-imaging" "rosbag" "roslib" "rospy" "rqt_bag" "rqt_gui" "rqt_gui_py" "rqt_plot" "sensor_msgs" "std_msgs")
set(rqt_bag_plugins_RUN_DEPENDS "geometry_msgs" "python-cairo" "python-imaging" "rosbag" "roslib" "rospy" "rqt_bag" "rqt_gui" "rqt_gui_py" "rqt_plot" "sensor_msgs" "std_msgs")
set(rqt_bag_plugins_TEST_DEPENDS )
set(rqt_bag_plugins_DOC_DEPENDS )
set(rqt_bag_plugins_DEPRECATED "")