set(rqt_bag_plugins_SETUP_PY_VERSION "0.3.13")
set(rqt_bag_plugins_SETUP_PY_SCRIPTS "")
set(rqt_bag_plugins_SETUP_PY_PACKAGES "rqt_bag_plugins")
set(rqt_bag_plugins_SETUP_PY_PACKAGE_DIRS "src/rqt_bag_plugins")
set(rqt_bag_plugins_SETUP_PY_MODULES "")
set(rqt_bag_plugins_SETUP_PY_MODULE_DIRS "")