set(_CATKIN_CURRENT_PACKAGE "rqt_shell")
set(rqt_shell_VERSION "0.3.13")
set(rqt_shell_MAINTAINER "Dorian Scholz <scholz@sim.tu-darmstadt.de>")
set(rqt_shell_PACKAGE_FORMAT "1")
set(rqt_shell_BUILD_DEPENDS )
set(rqt_shell_BUILD_EXPORT_DEPENDS "python-rospkg" "qt_gui" "qt_gui_py_common" "rqt_gui" "rqt_gui_py")
set(rqt_shell_BUILDTOOL_DEPENDS "catkin")
set(rqt_shell_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_shell_EXEC_DEPENDS "python-rospkg" "qt_gui" "qt_gui_py_common" "rqt_gui" "rqt_gui_py")
set(rqt_shell_RUN_DEPENDS "python-rospkg" "qt_gui" "qt_gui_py_common" "rqt_gui" "rqt_gui_py")
set(rqt_shell_TEST_DEPENDS )
set(rqt_shell_DOC_DEPENDS )
set(rqt_shell_DEPRECATED "")