set(rqt_shell_SETUP_PY_VERSION "0.3.13")
set(rqt_shell_SETUP_PY_SCRIPTS "")
set(rqt_shell_SETUP_PY_PACKAGES "rqt_shell")
set(rqt_shell_SETUP_PY_PACKAGE_DIRS "src/rqt_shell")
set(rqt_shell_SETUP_PY_MODULES "")
set(rqt_shell_SETUP_PY_MODULE_DIRS "")