set(_CATKIN_CURRENT_PACKAGE "convex_decomposition")
set(convex_decomposition_VERSION "0.1.10")
set(convex_decomposition_MAINTAINER "Bryce Vondervoort <bvondervoort@clearpathrobotics.com>")
set(convex_decomposition_PACKAGE_FORMAT "1")
set(convex_decomposition_BUILD_DEPENDS "unzip")
set(convex_decomposition_BUILD_EXPORT_DEPENDS "unzip")
set(convex_decomposition_BUILDTOOL_DEPENDS "catkin")
set(convex_decomposition_BUILDTOOL_EXPORT_DEPENDS )
set(convex_decomposition_EXEC_DEPENDS "unzip")
set(convex_decomposition_RUN_DEPENDS "unzip")
set(convex_decomposition_TEST_DEPENDS )
set(convex_decomposition_DOC_DEPENDS )
set(convex_decomposition_DEPRECATED "")