# CMake generated Testfile for 
# Source directory: /opt/ros_catkin_ws/src/interactive_markers
# Build directory: /opt/ros_catkin_ws/build_isolated/interactive_markers
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_interactive_markers_rostest_test_cpp_server.test "/opt/ros_catkin_ws/build_isolated/interactive_markers/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/interactive_markers/test_results/interactive_markers/rostest-test_cpp_server.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/interactive_markers --package=interactive_markers --results-filename test_cpp_server.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/interactive_markers/test_results\" /opt/ros_catkin_ws/src/interactive_markers/test/cpp_server.test ")
add_test(_ctest_interactive_markers_rostest_test_cpp_client.test "/opt/ros_catkin_ws/build_isolated/interactive_markers/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/interactive_markers/test_results/interactive_markers/rostest-test_cpp_client.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/interactive_markers --package=interactive_markers --results-filename test_cpp_client.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/interactive_markers/test_results\" /opt/ros_catkin_ws/src/interactive_markers/test/cpp_client.test ")
add_test(_ctest_interactive_markers_rostest_test_cpp_server_client.test "/opt/ros_catkin_ws/build_isolated/interactive_markers/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/interactive_markers/test_results/interactive_markers/rostest-test_cpp_server_client.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/interactive_markers --package=interactive_markers --results-filename test_cpp_server_client.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/interactive_markers/test_results\" /opt/ros_catkin_ws/src/interactive_markers/test/cpp_server_client.test ")
subdirs(gtest)
