# CMake generated Testfile for 
# Source directory: /opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials
# Build directory: /opt/ros_catkin_ws/build_isolated/rospy_tutorials
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rospy_tutorials_rostest_test_test-add-two-ints.launch "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-add-two-ints.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-add-two-ints.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-add-two-ints.launch ")
add_test(_ctest_rospy_tutorials_rostest_test_test-peer-subscribe-notify.launch "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-peer-subscribe-notify.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-peer-subscribe-notify.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-peer-subscribe-notify.launch ")
add_test(_ctest_rospy_tutorials_rostest_test_test-add-two-ints-with-roscpp-server.launch "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-add-two-ints-with-roscpp-server.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-add-two-ints-with-roscpp-server.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-add-two-ints-with-roscpp-server.launch ")
add_test(_ctest_rospy_tutorials_rostest_test_test-talker-listener.launch "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-talker-listener.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-talker-listener.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-talker-listener.launch ")
add_test(_ctest_rospy_tutorials_rostest_test_test-talker-listener-with-roscpp.launch "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-talker-listener-with-roscpp.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-talker-listener-with-roscpp.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-talker-listener-with-roscpp.launch ")
add_test(_ctest_rospy_tutorials_rostest_test_test-on-shutdown.launch "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-on-shutdown.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-on-shutdown.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-on-shutdown.launch ")
add_test(_ctest_rospy_tutorials_rostest_test_test-connection-header.launch "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-connection-header.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-connection-header.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /opt/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-connection-header.launch ")
subdirs(gtest)
