set(_CATKIN_CURRENT_PACKAGE "actionlib")
set(actionlib_VERSION "1.11.5")
set(actionlib_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(actionlib_PACKAGE_FORMAT "1")
set(actionlib_BUILD_DEPENDS "actionlib_msgs" "boost" "message_generation" "roscpp" "rospy" "rostest" "std_msgs")
set(actionlib_BUILD_EXPORT_DEPENDS "actionlib_msgs" "boost" "message_runtime" "roscpp" "rospy" "rostest" "std_msgs")
set(actionlib_BUILDTOOL_DEPENDS "catkin")
set(actionlib_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(actionlib_BUILDTOOL_EXPORT_DEPENDS )
set(actionlib_EXEC_DEPENDS "actionlib_msgs" "boost" "message_runtime" "roscpp" "rospy" "rostest" "std_msgs")
set(actionlib_RUN_DEPENDS "actionlib_msgs" "boost" "message_runtime" "roscpp" "rospy" "rostest" "std_msgs")
set(actionlib_TEST_DEPENDS "rosnode")
set(actionlib_DOC_DEPENDS )
set(actionlib_DEPRECATED "")