# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Accel.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/AccelStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/AccelWithCovariance.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/AccelWithCovarianceStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Inertia.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/InertiaStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Point.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Point32.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/PointStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Polygon.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/PolygonStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Pose2D.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Pose.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/PoseArray.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/PoseStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/PoseWithCovariance.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/PoseWithCovarianceStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Quaternion.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/QuaternionStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Transform.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/TransformStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Twist.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/TwistStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/TwistWithCovariance.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/TwistWithCovarianceStamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Vector3.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Vector3Stamped.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/Wrench.msg;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg/WrenchStamped.msg"
services_str = ""
pkg_name = "geometry_msgs"
dependencies_str = "std_msgs"
langs = "gencpp;geneus;genlisp;genpy"
dep_include_paths_str = "geometry_msgs;/opt/ros_catkin_ws/src/common_msgs/geometry_msgs/msg;std_msgs;/opt/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros_catkin_ws/install_isolated/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
