set(_CATKIN_CURRENT_PACKAGE "rosunit")
set(rosunit_VERSION "1.12.7")
set(rosunit_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosunit_PACKAGE_FORMAT "1")
set(rosunit_BUILD_DEPENDS )
set(rosunit_BUILD_EXPORT_DEPENDS "python-rospkg" "roslib")
set(rosunit_BUILDTOOL_DEPENDS "catkin")
set(rosunit_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(rosunit_BUILDTOOL_EXPORT_DEPENDS )
set(rosunit_EXEC_DEPENDS "python-rospkg" "roslib")
set(rosunit_RUN_DEPENDS "python-rospkg" "roslib")
set(rosunit_TEST_DEPENDS )
set(rosunit_DOC_DEPENDS )
set(rosunit_DEPRECATED "")