set(rosunit_SETUP_PY_VERSION "1.12.7")
set(rosunit_SETUP_PY_SCRIPTS "scripts/rosunit")
set(rosunit_SETUP_PY_PACKAGES "rosunit")
set(rosunit_SETUP_PY_PACKAGE_DIRS "src/rosunit")
set(rosunit_SETUP_PY_MODULES "")
set(rosunit_SETUP_PY_MODULE_DIRS "")