set(_CATKIN_CURRENT_PACKAGE "rqt_rviz")
set(rqt_rviz_VERSION "0.4.3")
set(rqt_rviz_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_rviz_PACKAGE_FORMAT "1")
set(rqt_rviz_BUILD_DEPENDS "boost" "pluginlib" "rqt_gui" "rqt_gui_cpp" "rviz")
set(rqt_rviz_BUILD_EXPORT_DEPENDS "boost" "pluginlib" "rqt_gui" "rqt_gui_cpp" "rviz")
set(rqt_rviz_BUILDTOOL_DEPENDS "catkin")
set(rqt_rviz_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_rviz_EXEC_DEPENDS "boost" "pluginlib" "rqt_gui" "rqt_gui_cpp" "rviz")
set(rqt_rviz_RUN_DEPENDS "boost" "pluginlib" "rqt_gui" "rqt_gui_cpp" "rviz")
set(rqt_rviz_TEST_DEPENDS )
set(rqt_rviz_DOC_DEPENDS )
set(rqt_rviz_DEPRECATED "")