set(_CATKIN_CURRENT_PACKAGE "rqt_topic")
set(rqt_topic_VERSION "0.3.13")
set(rqt_topic_MAINTAINER "Dorian Scholz <scholz@sim.tu-darmstadt.de>")
set(rqt_topic_PACKAGE_FORMAT "1")
set(rqt_topic_BUILD_DEPENDS )
set(rqt_topic_BUILD_EXPORT_DEPENDS "python-rospkg" "rostopic" "rqt_gui" "rqt_gui_py" "std_msgs")
set(rqt_topic_BUILDTOOL_DEPENDS "catkin")
set(rqt_topic_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_topic_EXEC_DEPENDS "python-rospkg" "rostopic" "rqt_gui" "rqt_gui_py" "std_msgs")
set(rqt_topic_RUN_DEPENDS "python-rospkg" "rostopic" "rqt_gui" "rqt_gui_py" "std_msgs")
set(rqt_topic_TEST_DEPENDS )
set(rqt_topic_DOC_DEPENDS )
set(rqt_topic_DEPRECATED "")