set(_CATKIN_CURRENT_PACKAGE "bond")
set(bond_VERSION "1.7.16")
set(bond_MAINTAINER "Esteve Fernandez <esteve@osrfoundation.org>")
set(bond_PACKAGE_FORMAT "1")
set(bond_BUILD_DEPENDS "message_generation" "std_msgs")
set(bond_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs")
set(bond_BUILDTOOL_DEPENDS "catkin")
set(bond_BUILDTOOL_EXPORT_DEPENDS )
set(bond_EXEC_DEPENDS "message_runtime" "std_msgs")
set(bond_RUN_DEPENDS "message_runtime" "std_msgs")
set(bond_TEST_DEPENDS )
set(bond_DOC_DEPENDS )
set(bond_DEPRECATED "")