set(_CATKIN_CURRENT_PACKAGE "ivcon")
set(ivcon_VERSION "0.1.5")
set(ivcon_MAINTAINER "Devon Ash <dash@clearpathrobotics.com>")
set(ivcon_PACKAGE_FORMAT "1")
set(ivcon_BUILD_DEPENDS )
set(ivcon_BUILD_EXPORT_DEPENDS )
set(ivcon_BUILDTOOL_DEPENDS "catkin")
set(ivcon_BUILDTOOL_EXPORT_DEPENDS )
set(ivcon_EXEC_DEPENDS )
set(ivcon_RUN_DEPENDS )
set(ivcon_TEST_DEPENDS )
set(ivcon_DOC_DEPENDS )
set(ivcon_DEPRECATED "")