set(_CATKIN_CURRENT_PACKAGE "roscpp_traits")
set(roscpp_traits_VERSION "0.5.7")
set(roscpp_traits_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(roscpp_traits_PACKAGE_FORMAT "1")
set(roscpp_traits_BUILD_DEPENDS )
set(roscpp_traits_BUILD_EXPORT_DEPENDS "cpp_common" "rostime")
set(roscpp_traits_BUILDTOOL_DEPENDS "catkin")
set(roscpp_traits_BUILDTOOL_EXPORT_DEPENDS )
set(roscpp_traits_EXEC_DEPENDS "cpp_common" "rostime")
set(roscpp_traits_RUN_DEPENDS "cpp_common" "rostime")
set(roscpp_traits_TEST_DEPENDS )
set(roscpp_traits_DOC_DEPENDS )
set(roscpp_traits_DEPRECATED "")