set(_CATKIN_CURRENT_PACKAGE "angles")
set(angles_VERSION "1.9.10")
set(angles_MAINTAINER "Ioan Sucan <isucan@willowgarage.com>")
set(angles_PACKAGE_FORMAT "1")
set(angles_BUILD_DEPENDS )
set(angles_BUILD_EXPORT_DEPENDS )
set(angles_BUILDTOOL_DEPENDS "catkin")
set(angles_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(angles_BUILDTOOL_EXPORT_DEPENDS )
set(angles_EXEC_DEPENDS )
set(angles_RUN_DEPENDS )
set(angles_TEST_DEPENDS )
set(angles_DOC_DEPENDS )
set(angles_DEPRECATED "")