set(_CATKIN_CURRENT_PACKAGE "std_srvs")
set(std_srvs_VERSION "1.11.2")
set(std_srvs_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(std_srvs_PACKAGE_FORMAT "1")
set(std_srvs_BUILD_DEPENDS "message_generation")
set(std_srvs_BUILD_EXPORT_DEPENDS "message_runtime")
set(std_srvs_BUILDTOOL_DEPENDS "catkin")
set(std_srvs_BUILDTOOL_EXPORT_DEPENDS )
set(std_srvs_EXEC_DEPENDS "message_runtime")
set(std_srvs_RUN_DEPENDS "message_runtime")
set(std_srvs_TEST_DEPENDS )
set(std_srvs_DOC_DEPENDS )
set(std_srvs_DEPRECATED "")