set(_CATKIN_CURRENT_PACKAGE "rqt_publisher")
set(rqt_publisher_VERSION "0.3.13")
set(rqt_publisher_MAINTAINER "Dorian Scholz <scholz@sim.tu-darmstadt.de>")
set(rqt_publisher_PACKAGE_FORMAT "1")
set(rqt_publisher_BUILD_DEPENDS )
set(rqt_publisher_BUILD_EXPORT_DEPENDS "python-rospkg" "qt_gui_py_common" "roslib" "rosmsg" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_publisher_BUILD_EXPORT_DEPENDS_rosmsg_VERSION_GTE "1.9.49")
set(rqt_publisher_BUILDTOOL_DEPENDS "catkin")
set(rqt_publisher_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_publisher_EXEC_DEPENDS "python-rospkg" "qt_gui_py_common" "roslib" "rosmsg" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_publisher_EXEC_DEPENDS_rosmsg_VERSION_GTE "1.9.49")
set(rqt_publisher_RUN_DEPENDS "python-rospkg" "qt_gui_py_common" "roslib" "rosmsg" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_publisher_RUN_DEPENDS_rosmsg_VERSION_GTE "1.9.49")
set(rqt_publisher_TEST_DEPENDS )
set(rqt_publisher_DOC_DEPENDS )
set(rqt_publisher_DEPRECATED "")