set(rqt_publisher_SETUP_PY_VERSION "0.3.13")
set(rqt_publisher_SETUP_PY_SCRIPTS "")
set(rqt_publisher_SETUP_PY_PACKAGES "rqt_publisher")
set(rqt_publisher_SETUP_PY_PACKAGE_DIRS "src/rqt_publisher")
set(rqt_publisher_SETUP_PY_MODULES "")
set(rqt_publisher_SETUP_PY_MODULE_DIRS "")