set(rosservice_SETUP_PY_VERSION "1.11.19")
set(rosservice_SETUP_PY_SCRIPTS "scripts/rosservice")
set(rosservice_SETUP_PY_PACKAGES "rosservice")
set(rosservice_SETUP_PY_PACKAGE_DIRS "src/rosservice")
set(rosservice_SETUP_PY_MODULES "")
set(rosservice_SETUP_PY_MODULE_DIRS "")