set(_CATKIN_CURRENT_PACKAGE "eigen_conversions")
set(eigen_conversions_VERSION "1.11.8")
set(eigen_conversions_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(eigen_conversions_PACKAGE_FORMAT "1")
set(eigen_conversions_BUILD_DEPENDS "cmake_modules" "geometry_msgs" "eigen" "orocos_kdl" "std_msgs")
set(eigen_conversions_BUILD_EXPORT_DEPENDS "geometry_msgs" "eigen" "orocos_kdl" "std_msgs")
set(eigen_conversions_BUILDTOOL_DEPENDS "catkin")
set(eigen_conversions_BUILDTOOL_EXPORT_DEPENDS )
set(eigen_conversions_EXEC_DEPENDS "geometry_msgs" "eigen" "orocos_kdl" "std_msgs")
set(eigen_conversions_RUN_DEPENDS "geometry_msgs" "eigen" "orocos_kdl" "std_msgs")
set(eigen_conversions_TEST_DEPENDS )
set(eigen_conversions_DOC_DEPENDS )
set(eigen_conversions_DEPRECATED "")