set(_CATKIN_CURRENT_PACKAGE "turtle_tf2")
set(turtle_tf2_VERSION "0.2.2")
set(turtle_tf2_MAINTAINER "Denis Štogl <denis.stogl@mailbox.org>")
set(turtle_tf2_PACKAGE_FORMAT "1")
set(turtle_tf2_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "tf2" "tf2_ros" "turtlesim")
set(turtle_tf2_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "tf2" "tf2_ros" "turtlesim")
set(turtle_tf2_BUILDTOOL_DEPENDS "catkin")
set(turtle_tf2_BUILDTOOL_EXPORT_DEPENDS )
set(turtle_tf2_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "tf2" "tf2_ros" "turtlesim")
set(turtle_tf2_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "tf2" "tf2_ros" "turtlesim")
set(turtle_tf2_TEST_DEPENDS )
set(turtle_tf2_DOC_DEPENDS )
set(turtle_tf2_DEPRECATED "")