set(_CATKIN_CURRENT_PACKAGE "qt_gui")
set(qt_gui_VERSION "0.2.30")
set(qt_gui_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(qt_gui_PACKAGE_FORMAT "1")
set(qt_gui_BUILD_DEPENDS "qt4-qmake" "python-qt-bindings")
set(qt_gui_BUILD_EXPORT_DEPENDS "python_qt_binding" "python-rospkg" "tango-icon-theme")
set(qt_gui_BUILDTOOL_DEPENDS "catkin")
set(qt_gui_BUILDTOOL_EXPORT_DEPENDS )
set(qt_gui_EXEC_DEPENDS "python_qt_binding" "python-rospkg" "tango-icon-theme")
set(qt_gui_RUN_DEPENDS "python_qt_binding" "python-rospkg" "tango-icon-theme")
set(qt_gui_TEST_DEPENDS )
set(qt_gui_DOC_DEPENDS )
set(qt_gui_DEPRECATED "")