set(_CATKIN_CURRENT_PACKAGE "rviz")
set(rviz_VERSION "1.11.14")
set(rviz_MAINTAINER "David Gossow <dgossow@gmail.com>, William Woodall <william@osrfoundation.org>")
set(rviz_PACKAGE_FORMAT "1")
set(rviz_BUILD_DEPENDS "assimp-dev" "cmake_modules" "eigen" "geometry_msgs" "image_geometry" "image_transport" "interactive_markers" "laser_geometry" "libogre-dev" "libqt4-dev" "libqt4-opengl-dev" "map_msgs" "message_filters" "nav_msgs" "pluginlib" "python_qt_binding" "resource_retriever" "rosbag" "rosconsole" "roscpp" "roslib" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "tf" "tinyxml" "urdf" "visualization_msgs" "yaml-cpp" "opengl")
set(rviz_BUILD_EXPORT_DEPENDS "assimp" "eigen" "geometry_msgs" "image_geometry" "image_transport" "interactive_markers" "laser_geometry" "libogre-dev" "libqt4-dev" "libqt4-opengl-dev" "map_msgs" "media_export" "message_filters" "nav_msgs" "pluginlib" "python_qt_binding" "resource_retriever" "rosbag" "rosconsole" "roscpp" "roslib" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "tf" "tinyxml" "urdf" "visualization_msgs" "yaml-cpp" "opengl")
set(rviz_BUILDTOOL_DEPENDS "catkin")
set(rviz_BUILDTOOL_EXPORT_DEPENDS )
set(rviz_EXEC_DEPENDS "assimp" "eigen" "geometry_msgs" "image_geometry" "image_transport" "interactive_markers" "laser_geometry" "libogre-dev" "libqt4-dev" "libqt4-opengl-dev" "map_msgs" "media_export" "message_filters" "nav_msgs" "pluginlib" "python_qt_binding" "resource_retriever" "rosbag" "rosconsole" "roscpp" "roslib" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "tf" "tinyxml" "urdf" "visualization_msgs" "yaml-cpp" "opengl")
set(rviz_RUN_DEPENDS "assimp" "eigen" "geometry_msgs" "image_geometry" "image_transport" "interactive_markers" "laser_geometry" "libogre-dev" "libqt4-dev" "libqt4-opengl-dev" "map_msgs" "media_export" "message_filters" "nav_msgs" "pluginlib" "python_qt_binding" "resource_retriever" "rosbag" "rosconsole" "roscpp" "roslib" "rospy" "sensor_msgs" "std_msgs" "std_srvs" "tf" "tinyxml" "urdf" "visualization_msgs" "yaml-cpp" "opengl")
set(rviz_TEST_DEPENDS )
set(rviz_DOC_DEPENDS )
set(rviz_DEPRECATED "")