set(_CATKIN_CURRENT_PACKAGE "rosbuild")
set(rosbuild_VERSION "1.12.7")
set(rosbuild_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosbuild_PACKAGE_FORMAT "1")
set(rosbuild_BUILD_DEPENDS "pkg-config")
set(rosbuild_BUILD_EXPORT_DEPENDS "catkin" "message_generation" "message_runtime")
set(rosbuild_BUILDTOOL_DEPENDS "catkin")
set(rosbuild_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(rosbuild_BUILDTOOL_EXPORT_DEPENDS )
set(rosbuild_EXEC_DEPENDS "catkin" "message_generation" "message_runtime")
set(rosbuild_RUN_DEPENDS "catkin" "message_generation" "message_runtime")
set(rosbuild_TEST_DEPENDS )
set(rosbuild_DOC_DEPENDS )
set(rosbuild_DEPRECATED "")