set(_CATKIN_CURRENT_PACKAGE "smach")
set(smach_VERSION "2.0.0")
set(smach_MAINTAINER "Jonathan Bohren <jbo@jhu.edu>")
set(smach_PACKAGE_FORMAT "1")
set(smach_BUILD_DEPENDS )
set(smach_BUILD_EXPORT_DEPENDS )
set(smach_BUILDTOOL_DEPENDS "catkin")
set(smach_BUILDTOOL_EXPORT_DEPENDS )
set(smach_EXEC_DEPENDS )
set(smach_RUN_DEPENDS )
set(smach_TEST_DEPENDS )
set(smach_DOC_DEPENDS )
set(smach_DEPRECATED "")