set(_CATKIN_CURRENT_PACKAGE "diagnostic_common_diagnostics")
set(diagnostic_common_diagnostics_VERSION "1.8.9")
set(diagnostic_common_diagnostics_MAINTAINER "Austin Hendrix <namniart@gmail.com>, Brice Rebsamen <brice.rebsamen@gmail.com>")
set(diagnostic_common_diagnostics_PACKAGE_FORMAT "1")
set(diagnostic_common_diagnostics_BUILD_DEPENDS "rospy" "diagnostic_updater")
set(diagnostic_common_diagnostics_BUILD_EXPORT_DEPENDS "diagnostic_updater" "hddtemp" "rospy" "tf")
set(diagnostic_common_diagnostics_BUILDTOOL_DEPENDS "catkin")
set(diagnostic_common_diagnostics_BUILDTOOL_EXPORT_DEPENDS )
set(diagnostic_common_diagnostics_EXEC_DEPENDS "diagnostic_updater" "hddtemp" "rospy" "tf")
set(diagnostic_common_diagnostics_RUN_DEPENDS "diagnostic_updater" "hddtemp" "rospy" "tf")
set(diagnostic_common_diagnostics_TEST_DEPENDS )
set(diagnostic_common_diagnostics_DOC_DEPENDS )
set(diagnostic_common_diagnostics_DEPRECATED "")