set(_CATKIN_CURRENT_PACKAGE "rqt_tf_tree")
set(rqt_tf_tree_VERSION "0.4.3")
set(rqt_tf_tree_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_tf_tree_PACKAGE_FORMAT "1")
set(rqt_tf_tree_BUILD_DEPENDS )
set(rqt_tf_tree_BUILD_EXPORT_DEPENDS "geometry_msgs" "python-rospkg" "qt_dotgraph" "rospy" "rqt_graph" "rqt_gui" "rqt_gui_py" "tf2" "tf2_msgs" "tf2_ros")
set(rqt_tf_tree_BUILDTOOL_DEPENDS "catkin")
set(rqt_tf_tree_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_tf_tree_EXEC_DEPENDS "geometry_msgs" "python-rospkg" "qt_dotgraph" "rospy" "rqt_graph" "rqt_gui" "rqt_gui_py" "tf2" "tf2_msgs" "tf2_ros")
set(rqt_tf_tree_RUN_DEPENDS "geometry_msgs" "python-rospkg" "qt_dotgraph" "rospy" "rqt_graph" "rqt_gui" "rqt_gui_py" "tf2" "tf2_msgs" "tf2_ros")
set(rqt_tf_tree_TEST_DEPENDS "python-mock")
set(rqt_tf_tree_DOC_DEPENDS )
set(rqt_tf_tree_DEPRECATED "")