set(rqt_tf_tree_SETUP_PY_VERSION "0.4.3")
set(rqt_tf_tree_SETUP_PY_SCRIPTS "")
set(rqt_tf_tree_SETUP_PY_PACKAGES "rqt_tf_tree")
set(rqt_tf_tree_SETUP_PY_PACKAGE_DIRS "src/rqt_tf_tree")
set(rqt_tf_tree_SETUP_PY_MODULES "")
set(rqt_tf_tree_SETUP_PY_MODULE_DIRS "")