set(_CATKIN_CURRENT_PACKAGE "common_tutorials")
set(common_tutorials_VERSION "0.1.8")
set(common_tutorials_MAINTAINER "Daniel Stonier <d.stonier@gmail.com>")
set(common_tutorials_PACKAGE_FORMAT "1")
set(common_tutorials_BUILD_DEPENDS )
set(common_tutorials_BUILD_EXPORT_DEPENDS "actionlib_tutorials" "nodelet_tutorial_math" "pluginlib_tutorials" "turtle_actionlib")
set(common_tutorials_BUILDTOOL_DEPENDS "catkin")
set(common_tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(common_tutorials_EXEC_DEPENDS "actionlib_tutorials" "nodelet_tutorial_math" "pluginlib_tutorials" "turtle_actionlib")
set(common_tutorials_RUN_DEPENDS "actionlib_tutorials" "nodelet_tutorial_math" "pluginlib_tutorials" "turtle_actionlib")
set(common_tutorials_TEST_DEPENDS )
set(common_tutorials_DOC_DEPENDS )
set(common_tutorials_DEPRECATED "")