set(_CATKIN_CURRENT_PACKAGE "random_numbers")
set(random_numbers_VERSION "0.3.0")
set(random_numbers_MAINTAINER "Ioan Sucan <isucan@willowgarage.com>")
set(random_numbers_PACKAGE_FORMAT "1")
set(random_numbers_BUILD_DEPENDS "boost")
set(random_numbers_BUILD_EXPORT_DEPENDS "boost")
set(random_numbers_BUILDTOOL_DEPENDS "catkin")
set(random_numbers_BUILDTOOL_EXPORT_DEPENDS )
set(random_numbers_EXEC_DEPENDS "boost")
set(random_numbers_RUN_DEPENDS "boost")
set(random_numbers_TEST_DEPENDS )
set(random_numbers_DOC_DEPENDS )
set(random_numbers_DEPRECATED "")