# CMake generated Testfile for 
# Source directory: /opt/ros_catkin_ws/src/robot_state_publisher
# Build directory: /opt/ros_catkin_ws/build_isolated/robot_state_publisher
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_robot_state_publisher_rostest_test_test_one_link.launch "/opt/ros_catkin_ws/build_isolated/robot_state_publisher/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/robot_state_publisher/test_results/robot_state_publisher/rostest-test_test_one_link.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/robot_state_publisher --package=robot_state_publisher --results-filename test_test_one_link.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/robot_state_publisher/test_results\" /opt/ros_catkin_ws/src/robot_state_publisher/test/test_one_link.launch ")
add_test(_ctest_robot_state_publisher_rostest_test_test_two_links_fixed_joint.launch "/opt/ros_catkin_ws/build_isolated/robot_state_publisher/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/robot_state_publisher/test_results/robot_state_publisher/rostest-test_test_two_links_fixed_joint.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/robot_state_publisher --package=robot_state_publisher --results-filename test_test_two_links_fixed_joint.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/robot_state_publisher/test_results\" /opt/ros_catkin_ws/src/robot_state_publisher/test/test_two_links_fixed_joint.launch ")
add_test(_ctest_robot_state_publisher_rostest_test_test_two_links_moving_joint.launch "/opt/ros_catkin_ws/build_isolated/robot_state_publisher/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/robot_state_publisher/test_results/robot_state_publisher/rostest-test_test_two_links_moving_joint.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/robot_state_publisher --package=robot_state_publisher --results-filename test_test_two_links_moving_joint.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/robot_state_publisher/test_results\" /opt/ros_catkin_ws/src/robot_state_publisher/test/test_two_links_moving_joint.launch ")
add_test(_ctest_robot_state_publisher_rostest_test_test_joint_states_bag.launch "/opt/ros_catkin_ws/build_isolated/robot_state_publisher/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/robot_state_publisher/test_results/robot_state_publisher/rostest-test_test_joint_states_bag.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/robot_state_publisher --package=robot_state_publisher --results-filename test_test_joint_states_bag.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/robot_state_publisher/test_results\" /opt/ros_catkin_ws/src/robot_state_publisher/test/test_joint_states_bag.launch ")
subdirs(gtest)
