set(_CATKIN_CURRENT_PACKAGE "cpp_common")
set(cpp_common_VERSION "0.5.7")
set(cpp_common_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(cpp_common_PACKAGE_FORMAT "1")
set(cpp_common_BUILD_DEPENDS "boost" "libconsole-bridge-dev")
set(cpp_common_BUILD_EXPORT_DEPENDS "boost" "libconsole-bridge-dev")
set(cpp_common_BUILDTOOL_DEPENDS "catkin")
set(cpp_common_BUILDTOOL_EXPORT_DEPENDS )
set(cpp_common_EXEC_DEPENDS "boost" "libconsole-bridge-dev")
set(cpp_common_RUN_DEPENDS "boost" "libconsole-bridge-dev")
set(cpp_common_TEST_DEPENDS )
set(cpp_common_DOC_DEPENDS )
set(cpp_common_DEPRECATED "")