set(_CATKIN_CURRENT_PACKAGE "control_msgs")
set(control_msgs_VERSION "1.3.1")
set(control_msgs_MAINTAINER "Adolfo Rodriguez Tsouroukdissian <adolfo.rodriguez@pal-robotics.com>")
set(control_msgs_PACKAGE_FORMAT "1")
set(control_msgs_BUILD_DEPENDS "message_generation" "std_msgs" "trajectory_msgs" "geometry_msgs" "actionlib_msgs")
set(control_msgs_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs" "trajectory_msgs" "geometry_msgs" "actionlib_msgs")
set(control_msgs_BUILDTOOL_DEPENDS "catkin")
set(control_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(control_msgs_EXEC_DEPENDS "message_runtime" "std_msgs" "trajectory_msgs" "geometry_msgs" "actionlib_msgs")
set(control_msgs_RUN_DEPENDS "message_runtime" "std_msgs" "trajectory_msgs" "geometry_msgs" "actionlib_msgs")
set(control_msgs_TEST_DEPENDS )
set(control_msgs_DOC_DEPENDS )
set(control_msgs_DEPRECATED "")