set(_CATKIN_CURRENT_PACKAGE "qt_dotgraph")
set(qt_dotgraph_VERSION "0.2.30")
set(qt_dotgraph_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(qt_dotgraph_PACKAGE_FORMAT "1")
set(qt_dotgraph_BUILD_DEPENDS )
set(qt_dotgraph_BUILD_EXPORT_DEPENDS "python-pydot" "python_qt_binding")
set(qt_dotgraph_BUILDTOOL_DEPENDS "catkin")
set(qt_dotgraph_BUILDTOOL_EXPORT_DEPENDS )
set(qt_dotgraph_EXEC_DEPENDS "python-pydot" "python_qt_binding")
set(qt_dotgraph_RUN_DEPENDS "python-pydot" "python_qt_binding")
set(qt_dotgraph_TEST_DEPENDS "python-pygraphviz")
set(qt_dotgraph_DOC_DEPENDS )
set(qt_dotgraph_DEPRECATED "")