set(_CATKIN_CURRENT_PACKAGE "rostime")
set(rostime_VERSION "0.5.7")
set(rostime_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rostime_PACKAGE_FORMAT "1")
set(rostime_BUILD_DEPENDS "boost" "cpp_common")
set(rostime_BUILD_EXPORT_DEPENDS "boost" "cpp_common")
set(rostime_BUILDTOOL_DEPENDS "catkin")
set(rostime_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(rostime_BUILDTOOL_EXPORT_DEPENDS )
set(rostime_EXEC_DEPENDS "boost" "cpp_common")
set(rostime_RUN_DEPENDS "boost" "cpp_common")
set(rostime_TEST_DEPENDS )
set(rostime_DOC_DEPENDS )
set(rostime_DEPRECATED "")