set(_CATKIN_CURRENT_PACKAGE "rqt_console")
set(rqt_console_VERSION "0.3.13")
set(rqt_console_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_console_PACKAGE_FORMAT "1")
set(rqt_console_BUILD_DEPENDS )
set(rqt_console_BUILD_EXPORT_DEPENDS "python-rospkg" "roslib" "rospy" "rqt_gui" "rqt_gui_py" "rqt_logger_level")
set(rqt_console_BUILDTOOL_DEPENDS "catkin")
set(rqt_console_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_console_EXEC_DEPENDS "python-rospkg" "roslib" "rospy" "rqt_gui" "rqt_gui_py" "rqt_logger_level")
set(rqt_console_RUN_DEPENDS "python-rospkg" "roslib" "rospy" "rqt_gui" "rqt_gui_py" "rqt_logger_level")
set(rqt_console_TEST_DEPENDS )
set(rqt_console_DOC_DEPENDS )
set(rqt_console_DEPRECATED "")