set(_CATKIN_CURRENT_PACKAGE "turtle_tf")
set(turtle_tf_VERSION "0.2.2")
set(turtle_tf_MAINTAINER "William Woodall <william@osrfoundation.org>")
set(turtle_tf_PACKAGE_FORMAT "1")
set(turtle_tf_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "tf" "turtlesim")
set(turtle_tf_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "tf" "turtlesim")
set(turtle_tf_BUILDTOOL_DEPENDS "catkin")
set(turtle_tf_BUILDTOOL_EXPORT_DEPENDS )
set(turtle_tf_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "tf" "turtlesim")
set(turtle_tf_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs" "tf" "turtlesim")
set(turtle_tf_TEST_DEPENDS )
set(turtle_tf_DOC_DEPENDS )
set(turtle_tf_DEPRECATED "")