# CMake generated Testfile for 
# Source directory: /opt/ros_catkin_ws/src/geometry/tf_conversions
# Build directory: /opt/ros_catkin_ws/build_isolated/tf_conversions
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_tf_conversions_gtest_test_eigen_tf "/opt/ros_catkin_ws/build_isolated/tf_conversions/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf_conversions/test_results/tf_conversions/gtest-test_eigen_tf.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/tf_conversions/lib/tf_conversions/test_eigen_tf --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/tf_conversions/test_results/tf_conversions/gtest-test_eigen_tf.xml")
add_test(_ctest_tf_conversions_gtest_test_kdl_tf "/opt/ros_catkin_ws/build_isolated/tf_conversions/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf_conversions/test_results/tf_conversions/gtest-test_kdl_tf.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/tf_conversions/lib/tf_conversions/test_kdl_tf --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/tf_conversions/test_results/tf_conversions/gtest-test_kdl_tf.xml")
add_test(_ctest_tf_conversions_nosetests_test.posemath.py "/opt/ros_catkin_ws/build_isolated/tf_conversions/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf_conversions/test_results/tf_conversions/nosetests-test.posemath.py.xml" "--return-code" "/usr/bin/cmake -E make_directory /opt/ros_catkin_ws/build_isolated/tf_conversions/test_results/tf_conversions" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /opt/ros_catkin_ws/src/geometry/tf_conversions/test/posemath.py --with-xunit --xunit-file=/opt/ros_catkin_ws/build_isolated/tf_conversions/test_results/tf_conversions/nosetests-test.posemath.py.xml")
subdirs(gtest)
