set(_CATKIN_CURRENT_PACKAGE "rqt_action")
set(rqt_action_VERSION "0.3.13")
set(rqt_action_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_action_PACKAGE_FORMAT "1")
set(rqt_action_BUILD_DEPENDS )
set(rqt_action_BUILD_EXPORT_DEPENDS "rospy" "rqt_msg" "rqt_py_common")
set(rqt_action_BUILDTOOL_DEPENDS "catkin")
set(rqt_action_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_action_EXEC_DEPENDS "rospy" "rqt_msg" "rqt_py_common")
set(rqt_action_RUN_DEPENDS "rospy" "rqt_msg" "rqt_py_common")
set(rqt_action_TEST_DEPENDS )
set(rqt_action_DOC_DEPENDS )
set(rqt_action_DEPRECATED "")