set(_CATKIN_CURRENT_PACKAGE "visualization_marker_tutorials")
set(visualization_marker_tutorials_VERSION "0.9.2")
set(visualization_marker_tutorials_MAINTAINER "William Woodall <william@osrfoundation.org>")
set(visualization_marker_tutorials_PACKAGE_FORMAT "1")
set(visualization_marker_tutorials_BUILD_DEPENDS "roscpp" "visualization_msgs")
set(visualization_marker_tutorials_BUILD_EXPORT_DEPENDS "roscpp" "visualization_msgs")
set(visualization_marker_tutorials_BUILDTOOL_DEPENDS "catkin")
set(visualization_marker_tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(visualization_marker_tutorials_EXEC_DEPENDS "roscpp" "visualization_msgs")
set(visualization_marker_tutorials_RUN_DEPENDS "roscpp" "visualization_msgs")
set(visualization_marker_tutorials_TEST_DEPENDS )
set(visualization_marker_tutorials_DOC_DEPENDS )
set(visualization_marker_tutorials_DEPRECATED "")