set(rosboost_cfg_SETUP_PY_VERSION "1.12.7")
set(rosboost_cfg_SETUP_PY_SCRIPTS "scripts/rosboost-cfg")
set(rosboost_cfg_SETUP_PY_PACKAGES "rosboost_cfg")
set(rosboost_cfg_SETUP_PY_PACKAGE_DIRS "src/rosboost_cfg")
set(rosboost_cfg_SETUP_PY_MODULES "")
set(rosboost_cfg_SETUP_PY_MODULE_DIRS "")