# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/BatteryState.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/CameraInfo.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/ChannelFloat32.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/CompressedImage.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/FluidPressure.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Illuminance.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Image.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Imu.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/JointState.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Joy.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/JoyFeedback.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/JoyFeedbackArray.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/LaserEcho.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/LaserScan.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/MagneticField.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/MultiDOFJointState.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/MultiEchoLaserScan.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/NavSatFix.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/NavSatStatus.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/PointCloud.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/PointCloud2.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/PointField.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Range.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/RegionOfInterest.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/RelativeHumidity.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Temperature.msg;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/TimeReference.msg"
services_str = "/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/srv/SetCameraInfo.srv"
pkg_name = "sensor_msgs"
dependencies_str = "geometry_msgs;std_msgs"
langs = "gencpp;geneus;genlisp;genpy"
dep_include_paths_str = "sensor_msgs;/opt/ros_catkin_ws/src/common_msgs/sensor_msgs/msg;geometry_msgs;/opt/ros_catkin_ws/install_isolated/share/geometry_msgs/cmake/../msg;std_msgs;/opt/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = 'TRUE' == 'TRUE'
genmsg_check_deps_script = "/opt/ros_catkin_ws/install_isolated/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
