set(_CATKIN_CURRENT_PACKAGE "rosbag_migration_rule")
set(rosbag_migration_rule_VERSION "1.0.0")
set(rosbag_migration_rule_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosbag_migration_rule_PACKAGE_FORMAT "1")
set(rosbag_migration_rule_BUILD_DEPENDS )
set(rosbag_migration_rule_BUILD_EXPORT_DEPENDS )
set(rosbag_migration_rule_BUILDTOOL_DEPENDS "catkin")
set(rosbag_migration_rule_BUILDTOOL_EXPORT_DEPENDS )
set(rosbag_migration_rule_EXEC_DEPENDS )
set(rosbag_migration_rule_RUN_DEPENDS )
set(rosbag_migration_rule_TEST_DEPENDS )
set(rosbag_migration_rule_DOC_DEPENDS )
set(rosbag_migration_rule_DEPRECATED "")