set(_CATKIN_CURRENT_PACKAGE "genmsg")
set(genmsg_VERSION "0.5.7")
set(genmsg_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(genmsg_PACKAGE_FORMAT "1")
set(genmsg_BUILD_DEPENDS )
set(genmsg_BUILD_EXPORT_DEPENDS "catkin")
set(genmsg_BUILDTOOL_DEPENDS "catkin")
set(genmsg_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.74")
set(genmsg_BUILDTOOL_EXPORT_DEPENDS )
set(genmsg_EXEC_DEPENDS "catkin")
set(genmsg_RUN_DEPENDS "catkin")
set(genmsg_TEST_DEPENDS )
set(genmsg_DOC_DEPENDS )
set(genmsg_DEPRECATED "")