set(_CATKIN_CURRENT_PACKAGE "nodelet_topic_tools")
set(nodelet_topic_tools_VERSION "1.9.4")
set(nodelet_topic_tools_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(nodelet_topic_tools_PACKAGE_FORMAT "1")
set(nodelet_topic_tools_BUILD_DEPENDS "boost" "dynamic_reconfigure")
set(nodelet_topic_tools_BUILD_EXPORT_DEPENDS "boost" "dynamic_reconfigure" "message_filters" "nodelet" "pluginlib" "roscpp")
set(nodelet_topic_tools_BUILDTOOL_DEPENDS "catkin")
set(nodelet_topic_tools_BUILDTOOL_EXPORT_DEPENDS )
set(nodelet_topic_tools_EXEC_DEPENDS "boost" "dynamic_reconfigure" "message_filters" "nodelet" "pluginlib" "roscpp")
set(nodelet_topic_tools_RUN_DEPENDS "boost" "dynamic_reconfigure" "message_filters" "nodelet" "pluginlib" "roscpp")
set(nodelet_topic_tools_TEST_DEPENDS )
set(nodelet_topic_tools_DOC_DEPENDS )
set(nodelet_topic_tools_DEPRECATED "")