set(_CATKIN_CURRENT_PACKAGE "rqt_robot_dashboard")
set(rqt_robot_dashboard_VERSION "0.4.3")
set(rqt_robot_dashboard_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_robot_dashboard_PACKAGE_FORMAT "1")
set(rqt_robot_dashboard_BUILD_DEPENDS )
set(rqt_robot_dashboard_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "python_qt_binding" "qt_gui" "rospy" "rqt_console" "rqt_gui" "rqt_gui_py" "rqt_nav_view" "rqt_robot_monitor")
set(rqt_robot_dashboard_BUILD_EXPORT_DEPENDS_rqt_console_VERSION_GTE "0.3.1")
set(rqt_robot_dashboard_BUILDTOOL_DEPENDS "catkin")
set(rqt_robot_dashboard_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_robot_dashboard_EXEC_DEPENDS "diagnostic_msgs" "python_qt_binding" "qt_gui" "rospy" "rqt_console" "rqt_gui" "rqt_gui_py" "rqt_nav_view" "rqt_robot_monitor")
set(rqt_robot_dashboard_EXEC_DEPENDS_rqt_console_VERSION_GTE "0.3.1")
set(rqt_robot_dashboard_RUN_DEPENDS "diagnostic_msgs" "python_qt_binding" "qt_gui" "rospy" "rqt_console" "rqt_gui" "rqt_gui_py" "rqt_nav_view" "rqt_robot_monitor")
set(rqt_robot_dashboard_RUN_DEPENDS_rqt_console_VERSION_GTE "0.3.1")
set(rqt_robot_dashboard_TEST_DEPENDS )
set(rqt_robot_dashboard_DOC_DEPENDS )
set(rqt_robot_dashboard_DEPRECATED "")