set(rqt_robot_dashboard_SETUP_PY_VERSION "0.4.3")
set(rqt_robot_dashboard_SETUP_PY_SCRIPTS "")
set(rqt_robot_dashboard_SETUP_PY_PACKAGES "rqt_robot_dashboard")
set(rqt_robot_dashboard_SETUP_PY_PACKAGE_DIRS "src/rqt_robot_dashboard")
set(rqt_robot_dashboard_SETUP_PY_MODULES "")
set(rqt_robot_dashboard_SETUP_PY_MODULE_DIRS "")