set(_CATKIN_CURRENT_PACKAGE "roscpp_core")
set(roscpp_core_VERSION "0.5.7")
set(roscpp_core_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(roscpp_core_PACKAGE_FORMAT "1")
set(roscpp_core_BUILD_DEPENDS )
set(roscpp_core_BUILD_EXPORT_DEPENDS "cpp_common" "roscpp_serialization" "roscpp_traits" "rostime")
set(roscpp_core_BUILDTOOL_DEPENDS "catkin")
set(roscpp_core_BUILDTOOL_EXPORT_DEPENDS )
set(roscpp_core_EXEC_DEPENDS "cpp_common" "roscpp_serialization" "roscpp_traits" "rostime")
set(roscpp_core_RUN_DEPENDS "cpp_common" "roscpp_serialization" "roscpp_traits" "rostime")
set(roscpp_core_TEST_DEPENDS )
set(roscpp_core_DOC_DEPENDS )
set(roscpp_core_DEPRECATED "")