# CMake generated Testfile for 
# Source directory: /opt/ros_catkin_ws/src/executive_smach/smach_ros
# Build directory: /opt/ros_catkin_ws/build_isolated/smach_ros
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_smach_ros_rostest_test_state_machine.test "/opt/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_state_machine.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_state_machine.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/smach_ros/test_results\" /opt/ros_catkin_ws/src/executive_smach/smach_ros/test/state_machine.test ")
add_test(_ctest_smach_ros_rostest_test_sequence.test "/opt/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_sequence.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_sequence.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/smach_ros/test_results\" /opt/ros_catkin_ws/src/executive_smach/smach_ros/test/sequence.test ")
add_test(_ctest_smach_ros_rostest_test_concurrence.test "/opt/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_concurrence.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_concurrence.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/smach_ros/test_results\" /opt/ros_catkin_ws/src/executive_smach/smach_ros/test/concurrence.test ")
add_test(_ctest_smach_ros_rostest_test_introspection.test "/opt/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_introspection.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_introspection.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/smach_ros/test_results\" /opt/ros_catkin_ws/src/executive_smach/smach_ros/test/introspection.test ")
add_test(_ctest_smach_ros_rostest_test_smach_actionlib.test "/opt/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_smach_actionlib.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_smach_actionlib.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/smach_ros/test_results\" /opt/ros_catkin_ws/src/executive_smach/smach_ros/test/smach_actionlib.test ")
subdirs(gtest)
