# CMake generated Testfile for 
# Source directory: /opt/ros_catkin_ws/src/ros_comm/message_filters
# Build directory: /opt/ros_catkin_ws/build_isolated/message_filters
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_message_filters_gtest_message_filters-msg_cache_unittest "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-msg_cache_unittest.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-msg_cache_unittest --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-msg_cache_unittest.xml")
add_test(_ctest_message_filters_gtest_message_filters-time_synchronizer_unittest "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-time_synchronizer_unittest.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-time_synchronizer_unittest --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-time_synchronizer_unittest.xml")
add_test(_ctest_message_filters_gtest_message_filters-test_synchronizer "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_synchronizer.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-test_synchronizer --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_synchronizer.xml")
add_test(_ctest_message_filters_gtest_message_filters-test_exact_time_policy "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_exact_time_policy.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-test_exact_time_policy --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_exact_time_policy.xml")
add_test(_ctest_message_filters_gtest_message_filters-test_approximate_time_policy "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_approximate_time_policy.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-test_approximate_time_policy --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_approximate_time_policy.xml")
add_test(_ctest_message_filters_gtest_message_filters-test_simple "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_simple.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-test_simple --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_simple.xml")
add_test(_ctest_message_filters_gtest_message_filters-test_chain "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_chain.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-test_chain --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_chain.xml")
add_test(_ctest_message_filters_rostest_test_time_sequencer_unittest.xml "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/rostest-test_time_sequencer_unittest.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_comm/message_filters --package=message_filters --results-filename test_time_sequencer_unittest.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/message_filters/test_results\" /opt/ros_catkin_ws/src/ros_comm/message_filters/test/time_sequencer_unittest.xml ")
add_test(_ctest_message_filters_rostest_test_test_subscriber.xml "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/rostest-test_test_subscriber.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_comm/message_filters --package=message_filters --results-filename test_test_subscriber.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/message_filters/test_results\" /opt/ros_catkin_ws/src/ros_comm/message_filters/test/test_subscriber.xml ")
add_test(_ctest_message_filters_nosetests_test.test_approxsync.py "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/nosetests-test.test_approxsync.py.xml" "--return-code" "/usr/bin/cmake -E make_directory /opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /opt/ros_catkin_ws/src/ros_comm/message_filters/test/test_approxsync.py --with-xunit --xunit-file=/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/nosetests-test.test_approxsync.py.xml")
add_test(_ctest_message_filters_nosetests_test.test_message_filters_cache.py "/opt/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/nosetests-test.test_message_filters_cache.py.xml" "--return-code" "/usr/bin/cmake -E make_directory /opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /opt/ros_catkin_ws/src/ros_comm/message_filters/test/test_message_filters_cache.py --with-xunit --xunit-file=/opt/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/nosetests-test.test_message_filters_cache.py.xml")
subdirs(gtest)
