set(roslint_SETUP_PY_VERSION "0.10.0")
set(roslint_SETUP_PY_SCRIPTS "")
set(roslint_SETUP_PY_PACKAGES "roslint")
set(roslint_SETUP_PY_PACKAGE_DIRS "src/roslint")
set(roslint_SETUP_PY_MODULES "")
set(roslint_SETUP_PY_MODULE_DIRS "")