set(_CATKIN_CURRENT_PACKAGE "diagnostics")
set(diagnostics_VERSION "1.8.9")
set(diagnostics_MAINTAINER "Brice Rebsamen <brice.rebsamen@gmail.com>, Austin Hendrix <namniart@gmail.com>")
set(diagnostics_PACKAGE_FORMAT "1")
set(diagnostics_BUILD_DEPENDS )
set(diagnostics_BUILD_EXPORT_DEPENDS "diagnostic_aggregator" "diagnostic_analysis" "diagnostic_common_diagnostics" "diagnostic_updater" "self_test")
set(diagnostics_BUILDTOOL_DEPENDS "catkin")
set(diagnostics_BUILDTOOL_EXPORT_DEPENDS )
set(diagnostics_EXEC_DEPENDS "diagnostic_aggregator" "diagnostic_analysis" "diagnostic_common_diagnostics" "diagnostic_updater" "self_test")
set(diagnostics_RUN_DEPENDS "diagnostic_aggregator" "diagnostic_analysis" "diagnostic_common_diagnostics" "diagnostic_updater" "self_test")
set(diagnostics_TEST_DEPENDS )
set(diagnostics_DOC_DEPENDS )
set(diagnostics_DEPRECATED "")