set(_CATKIN_CURRENT_PACKAGE "genpy")
set(genpy_VERSION "0.5.9")
set(genpy_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(genpy_PACKAGE_FORMAT "1")
set(genpy_BUILD_DEPENDS "genmsg")
set(genpy_BUILD_EXPORT_DEPENDS "genmsg")
set(genpy_BUILDTOOL_DEPENDS "catkin")
set(genpy_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(genpy_BUILDTOOL_EXPORT_DEPENDS )
set(genpy_EXEC_DEPENDS "genmsg")
set(genpy_RUN_DEPENDS "genmsg")
set(genpy_TEST_DEPENDS "python-yaml")
set(genpy_DOC_DEPENDS )
set(genpy_DEPRECATED "")