set(_CATKIN_CURRENT_PACKAGE "rqt_py_console")
set(rqt_py_console_VERSION "0.3.13")
set(rqt_py_console_MAINTAINER "Dorian Scholz <scholz@sim.tu-darmstadt.de>")
set(rqt_py_console_PACKAGE_FORMAT "1")
set(rqt_py_console_BUILD_DEPENDS )
set(rqt_py_console_BUILD_EXPORT_DEPENDS "python-rospkg" "qt_gui" "qt_gui_py_common" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_py_console_BUILDTOOL_DEPENDS "catkin")
set(rqt_py_console_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_py_console_EXEC_DEPENDS "python-rospkg" "qt_gui" "qt_gui_py_common" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_py_console_RUN_DEPENDS "python-rospkg" "qt_gui" "qt_gui_py_common" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_py_console_TEST_DEPENDS )
set(rqt_py_console_DOC_DEPENDS )
set(rqt_py_console_DEPRECATED "")