set(_CATKIN_CURRENT_PACKAGE "rqt_srv")
set(rqt_srv_VERSION "0.3.13")
set(rqt_srv_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_srv_PACKAGE_FORMAT "1")
set(rqt_srv_BUILD_DEPENDS )
set(rqt_srv_BUILD_EXPORT_DEPENDS "rosmsg" "rospy" "rqt_gui" "rqt_gui_py" "rqt_msg")
set(rqt_srv_BUILDTOOL_DEPENDS "catkin")
set(rqt_srv_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_srv_EXEC_DEPENDS "rosmsg" "rospy" "rqt_gui" "rqt_gui_py" "rqt_msg")
set(rqt_srv_RUN_DEPENDS "rosmsg" "rospy" "rqt_gui" "rqt_gui_py" "rqt_msg")
set(rqt_srv_TEST_DEPENDS )
set(rqt_srv_DOC_DEPENDS )
set(rqt_srv_DEPRECATED "")