set(rqt_srv_SETUP_PY_VERSION "0.3.13")
set(rqt_srv_SETUP_PY_SCRIPTS "")
set(rqt_srv_SETUP_PY_PACKAGES "rqt_srv")
set(rqt_srv_SETUP_PY_PACKAGE_DIRS "src/rqt_srv")
set(rqt_srv_SETUP_PY_MODULES "")
set(rqt_srv_SETUP_PY_MODULE_DIRS "")