set(_CATKIN_CURRENT_PACKAGE "rqt_service_caller")
set(rqt_service_caller_VERSION "0.3.13")
set(rqt_service_caller_MAINTAINER "Dorian Scholz <scholz@sim.tu-darmstadt.de>")
set(rqt_service_caller_PACKAGE_FORMAT "1")
set(rqt_service_caller_BUILD_DEPENDS )
set(rqt_service_caller_BUILD_EXPORT_DEPENDS "python-rospkg" "rosservice" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_service_caller_BUILDTOOL_DEPENDS "catkin")
set(rqt_service_caller_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_service_caller_EXEC_DEPENDS "python-rospkg" "rosservice" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_service_caller_RUN_DEPENDS "python-rospkg" "rosservice" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_service_caller_TEST_DEPENDS )
set(rqt_service_caller_DOC_DEPENDS )
set(rqt_service_caller_DEPRECATED "")