set(rqt_service_caller_SETUP_PY_VERSION "0.3.13")
set(rqt_service_caller_SETUP_PY_SCRIPTS "")
set(rqt_service_caller_SETUP_PY_PACKAGES "rqt_service_caller")
set(rqt_service_caller_SETUP_PY_PACKAGE_DIRS "src/rqt_service_caller")
set(rqt_service_caller_SETUP_PY_MODULES "")
set(rqt_service_caller_SETUP_PY_MODULE_DIRS "")