set(_CATKIN_CURRENT_PACKAGE "qt_gui_cpp")
set(qt_gui_cpp_VERSION "0.2.30")
set(qt_gui_cpp_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(qt_gui_cpp_PACKAGE_FORMAT "1")
set(qt_gui_cpp_BUILD_DEPENDS "libqt4-dev" "pkg-config" "pluginlib" "python_qt_binding" "qt4-qmake" "tinyxml")
set(qt_gui_cpp_BUILD_DEPENDS_pluginlib_VERSION_GTE "1.9.23")
set(qt_gui_cpp_BUILD_DEPENDS_python_qt_binding_VERSION_GTE "0.2.11")
set(qt_gui_cpp_BUILD_EXPORT_DEPENDS "pluginlib" "qt_gui")
set(qt_gui_cpp_BUILD_EXPORT_DEPENDS_pluginlib_VERSION_GTE "1.9.23")
set(qt_gui_cpp_BUILD_EXPORT_DEPENDS_qt_gui_VERSION_GTE "0.2.18")
set(qt_gui_cpp_BUILDTOOL_DEPENDS "catkin")
set(qt_gui_cpp_BUILDTOOL_EXPORT_DEPENDS )
set(qt_gui_cpp_EXEC_DEPENDS "pluginlib" "qt_gui")
set(qt_gui_cpp_EXEC_DEPENDS_pluginlib_VERSION_GTE "1.9.23")
set(qt_gui_cpp_EXEC_DEPENDS_qt_gui_VERSION_GTE "0.2.18")
set(qt_gui_cpp_RUN_DEPENDS "pluginlib" "qt_gui")
set(qt_gui_cpp_RUN_DEPENDS_pluginlib_VERSION_GTE "1.9.23")
set(qt_gui_cpp_RUN_DEPENDS_qt_gui_VERSION_GTE "0.2.18")
set(qt_gui_cpp_TEST_DEPENDS )
set(qt_gui_cpp_DOC_DEPENDS )
set(qt_gui_cpp_DEPRECATED "")