set(_CATKIN_CURRENT_PACKAGE "geneus")
set(geneus_VERSION "2.2.5")
set(geneus_MAINTAINER "Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>")
set(geneus_PACKAGE_FORMAT "1")
set(geneus_BUILD_DEPENDS "genmsg")
set(geneus_BUILD_EXPORT_DEPENDS "genmsg")
set(geneus_BUILDTOOL_DEPENDS "catkin")
set(geneus_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(geneus_BUILDTOOL_EXPORT_DEPENDS )
set(geneus_EXEC_DEPENDS "genmsg")
set(geneus_RUN_DEPENDS "genmsg")
set(geneus_TEST_DEPENDS )
set(geneus_DOC_DEPENDS )
set(geneus_DEPRECATED "")