set(_CATKIN_CURRENT_PACKAGE "rqt_gui_py")
set(rqt_gui_py_VERSION "0.2.14")
set(rqt_gui_py_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rqt_gui_py_PACKAGE_FORMAT "1")
set(rqt_gui_py_BUILD_DEPENDS "qt_gui" "rqt_gui" "rospy")
set(rqt_gui_py_BUILD_EXPORT_DEPENDS "qt_gui" "rqt_gui" "rospy")
set(rqt_gui_py_BUILD_EXPORT_DEPENDS_qt_gui_VERSION_GTE "0.2.17")
set(rqt_gui_py_BUILDTOOL_DEPENDS "catkin")
set(rqt_gui_py_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_gui_py_EXEC_DEPENDS "qt_gui" "rqt_gui" "rospy")
set(rqt_gui_py_EXEC_DEPENDS_qt_gui_VERSION_GTE "0.2.17")
set(rqt_gui_py_RUN_DEPENDS "qt_gui" "rqt_gui" "rospy")
set(rqt_gui_py_RUN_DEPENDS_qt_gui_VERSION_GTE "0.2.17")
set(rqt_gui_py_TEST_DEPENDS )
set(rqt_gui_py_DOC_DEPENDS )
set(rqt_gui_py_DEPRECATED "")