set(_CATKIN_CURRENT_PACKAGE "geometry_tutorials")
set(geometry_tutorials_VERSION "0.2.2")
set(geometry_tutorials_MAINTAINER "William Woodall <william@osrfoundation.org>")
set(geometry_tutorials_PACKAGE_FORMAT "1")
set(geometry_tutorials_BUILD_DEPENDS )
set(geometry_tutorials_BUILD_EXPORT_DEPENDS "turtle_tf" "turtle_tf2")
set(geometry_tutorials_BUILDTOOL_DEPENDS "catkin")
set(geometry_tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(geometry_tutorials_EXEC_DEPENDS "turtle_tf" "turtle_tf2")
set(geometry_tutorials_RUN_DEPENDS "turtle_tf" "turtle_tf2")
set(geometry_tutorials_TEST_DEPENDS )
set(geometry_tutorials_DOC_DEPENDS )
set(geometry_tutorials_DEPRECATED "")