set(_CATKIN_CURRENT_PACKAGE "interactive_markers")
set(interactive_markers_VERSION "1.11.1")
set(interactive_markers_MAINTAINER "William Woodall <william@osrfoundation.org>")
set(interactive_markers_PACKAGE_FORMAT "1")
set(interactive_markers_BUILD_DEPENDS "rosconsole" "roscpp" "rospy" "rostest" "std_msgs" "tf" "visualization_msgs")
set(interactive_markers_BUILD_EXPORT_DEPENDS "rosconsole" "roscpp" "rospy" "rostest" "std_msgs" "tf" "visualization_msgs")
set(interactive_markers_BUILDTOOL_DEPENDS "catkin")
set(interactive_markers_BUILDTOOL_EXPORT_DEPENDS )
set(interactive_markers_EXEC_DEPENDS "rosconsole" "roscpp" "rospy" "rostest" "std_msgs" "tf" "visualization_msgs")
set(interactive_markers_RUN_DEPENDS "rosconsole" "roscpp" "rospy" "rostest" "std_msgs" "tf" "visualization_msgs")
set(interactive_markers_TEST_DEPENDS )
set(interactive_markers_DOC_DEPENDS )
set(interactive_markers_DEPRECATED "")