set(_CATKIN_CURRENT_PACKAGE "media_export")
set(media_export_VERSION "0.2.0")
set(media_export_MAINTAINER "William Woodall <william@osrfoundation.org>")
set(media_export_PACKAGE_FORMAT "1")
set(media_export_BUILD_DEPENDS )
set(media_export_BUILD_EXPORT_DEPENDS )
set(media_export_BUILDTOOL_DEPENDS "catkin")
set(media_export_BUILDTOOL_EXPORT_DEPENDS )
set(media_export_EXEC_DEPENDS )
set(media_export_RUN_DEPENDS )
set(media_export_TEST_DEPENDS )
set(media_export_DOC_DEPENDS )
set(media_export_DEPRECATED "")