set(_CATKIN_CURRENT_PACKAGE "robot_state_publisher")
set(robot_state_publisher_VERSION "1.12.1")
set(robot_state_publisher_MAINTAINER "Ioan Sucan <isucan@google.com>, Jackie Kay <jackie@osrfoundation.org>")
set(robot_state_publisher_PACKAGE_FORMAT "1")
set(robot_state_publisher_BUILD_DEPENDS "eigen" "kdl_parser" "orocos_kdl" "rosconsole" "roscpp" "rostest" "rostime" "sensor_msgs" "tf" "tf2_ros" "tf2_kdl" "cmake_modules" "rostest")
set(robot_state_publisher_BUILD_DEPENDS_orocos_kdl_VERSION_GTE "1.3.0")
set(robot_state_publisher_BUILD_EXPORT_DEPENDS "catkin" "eigen" "kdl_parser" "orocos_kdl" "rosconsole" "roscpp" "rostime" "sensor_msgs" "tf" "tf2_ros" "tf2_kdl" "tf_conversions")
set(robot_state_publisher_BUILD_EXPORT_DEPENDS_orocos_kdl_VERSION_GTE "1.3.0")
set(robot_state_publisher_BUILDTOOL_DEPENDS "catkin")
set(robot_state_publisher_BUILDTOOL_EXPORT_DEPENDS )
set(robot_state_publisher_EXEC_DEPENDS "catkin" "eigen" "kdl_parser" "orocos_kdl" "rosconsole" "roscpp" "rostime" "sensor_msgs" "tf" "tf2_ros" "tf2_kdl" "tf_conversions")
set(robot_state_publisher_EXEC_DEPENDS_orocos_kdl_VERSION_GTE "1.3.0")
set(robot_state_publisher_RUN_DEPENDS "catkin" "eigen" "kdl_parser" "orocos_kdl" "rosconsole" "roscpp" "rostime" "sensor_msgs" "tf" "tf2_ros" "tf2_kdl" "tf_conversions")
set(robot_state_publisher_RUN_DEPENDS_orocos_kdl_VERSION_GTE "1.3.0")
set(robot_state_publisher_TEST_DEPENDS )
set(robot_state_publisher_DOC_DEPENDS )
set(robot_state_publisher_DEPRECATED "")