set(_CATKIN_CURRENT_PACKAGE "actionlib_tutorials")
set(actionlib_tutorials_VERSION "0.1.8")
set(actionlib_tutorials_MAINTAINER "Daniel Stonier <d.stonier@gmail.com>")
set(actionlib_tutorials_PACKAGE_FORMAT "1")
set(actionlib_tutorials_BUILD_DEPENDS "roscpp" "actionlib" "message_generation" "std_msgs" "actionlib_msgs")
set(actionlib_tutorials_BUILD_EXPORT_DEPENDS "roscpp" "actionlib" "message_runtime")
set(actionlib_tutorials_BUILDTOOL_DEPENDS "catkin")
set(actionlib_tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(actionlib_tutorials_EXEC_DEPENDS "roscpp" "actionlib" "message_runtime")
set(actionlib_tutorials_RUN_DEPENDS "roscpp" "actionlib" "message_runtime")
set(actionlib_tutorials_TEST_DEPENDS )
set(actionlib_tutorials_DOC_DEPENDS )
set(actionlib_tutorials_DEPRECATED "")