set(_CATKIN_CURRENT_PACKAGE "urdf_tutorial")
set(urdf_tutorial_VERSION "0.2.4")
set(urdf_tutorial_MAINTAINER "David V. Lu!! <davidvlu@gmail.com>")
set(urdf_tutorial_PACKAGE_FORMAT "1")
set(urdf_tutorial_BUILD_DEPENDS "urdf")
set(urdf_tutorial_BUILD_EXPORT_DEPENDS "urdf" "joint_state_publisher" "pr2_description" "robot_state_publisher" "rviz" "xacro")
set(urdf_tutorial_BUILDTOOL_DEPENDS "catkin")
set(urdf_tutorial_BUILDTOOL_EXPORT_DEPENDS )
set(urdf_tutorial_EXEC_DEPENDS "urdf" "joint_state_publisher" "pr2_description" "robot_state_publisher" "rviz" "xacro")
set(urdf_tutorial_RUN_DEPENDS "urdf" "joint_state_publisher" "pr2_description" "robot_state_publisher" "rviz" "xacro")
set(urdf_tutorial_TEST_DEPENDS )
set(urdf_tutorial_DOC_DEPENDS )
set(urdf_tutorial_DEPRECATED "")