set(_CATKIN_CURRENT_PACKAGE "ros")
set(ros_VERSION "1.12.7")
set(ros_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(ros_PACKAGE_FORMAT "1")
set(ros_BUILD_DEPENDS )
set(ros_BUILD_EXPORT_DEPENDS "catkin" "mk" "rosbuild" "roslang" "roslib" "rosbash" "rosboost_cfg" "rosclean" "roscreate" "rosmake" "rosunit")
set(ros_BUILDTOOL_DEPENDS "catkin")
set(ros_BUILDTOOL_EXPORT_DEPENDS )
set(ros_EXEC_DEPENDS "catkin" "mk" "rosbuild" "roslang" "roslib" "rosbash" "rosboost_cfg" "rosclean" "roscreate" "rosmake" "rosunit")
set(ros_RUN_DEPENDS "catkin" "mk" "rosbuild" "roslang" "roslib" "rosbash" "rosboost_cfg" "rosclean" "roscreate" "rosmake" "rosunit")
set(ros_TEST_DEPENDS )
set(ros_DOC_DEPENDS )
set(ros_DEPRECATED "")