set(_CATKIN_CURRENT_PACKAGE "rqt_logger_level")
set(rqt_logger_level_VERSION "0.3.13")
set(rqt_logger_level_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_logger_level_PACKAGE_FORMAT "1")
set(rqt_logger_level_BUILD_DEPENDS )
set(rqt_logger_level_BUILD_EXPORT_DEPENDS "python-rospkg" "rosnode" "rosservice" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_logger_level_BUILDTOOL_DEPENDS "catkin")
set(rqt_logger_level_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_logger_level_EXEC_DEPENDS "python-rospkg" "rosnode" "rosservice" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_logger_level_RUN_DEPENDS "python-rospkg" "rosnode" "rosservice" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_logger_level_TEST_DEPENDS )
set(rqt_logger_level_DOC_DEPENDS )
set(rqt_logger_level_DEPRECATED "")