set(_CATKIN_CURRENT_PACKAGE "genlisp")
set(genlisp_VERSION "0.4.15")
set(genlisp_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>, Georg Bartels <georg.bartels@cs.uni-bremen.de>")
set(genlisp_PACKAGE_FORMAT "1")
set(genlisp_BUILD_DEPENDS "genmsg")
set(genlisp_BUILD_EXPORT_DEPENDS "genmsg")
set(genlisp_BUILDTOOL_DEPENDS "catkin")
set(genlisp_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(genlisp_BUILDTOOL_EXPORT_DEPENDS )
set(genlisp_EXEC_DEPENDS "genmsg")
set(genlisp_RUN_DEPENDS "genmsg")
set(genlisp_TEST_DEPENDS )
set(genlisp_DOC_DEPENDS )
set(genlisp_DEPRECATED "")