set(_CATKIN_CURRENT_PACKAGE "rqt_robot_steering")
set(rqt_robot_steering_VERSION "0.4.3")
set(rqt_robot_steering_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_robot_steering_PACKAGE_FORMAT "1")
set(rqt_robot_steering_BUILD_DEPENDS )
set(rqt_robot_steering_BUILD_EXPORT_DEPENDS "geometry_msgs" "python-rospkg" "rostopic" "rqt_gui" "rqt_gui_py")
set(rqt_robot_steering_BUILDTOOL_DEPENDS "catkin")
set(rqt_robot_steering_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_robot_steering_EXEC_DEPENDS "geometry_msgs" "python-rospkg" "rostopic" "rqt_gui" "rqt_gui_py")
set(rqt_robot_steering_RUN_DEPENDS "geometry_msgs" "python-rospkg" "rostopic" "rqt_gui" "rqt_gui_py")
set(rqt_robot_steering_TEST_DEPENDS )
set(rqt_robot_steering_DOC_DEPENDS )
set(rqt_robot_steering_DEPRECATED "")