/*
 * Internal module API header file.
 *
 * Generated by SIP 4.17
 */

#ifndef _PyKDLAPI_H
#define _PyKDLAPI_H


#include <sip.h>

/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_ChainIkSolverVel_pinv_givens 0
#define sipName_ChainIkSolverVel_pinv_givens &sipStrings_PyKDL[0]
#define sipNameNr_ChainFkSolverVel_recursive 29
#define sipName_ChainFkSolverVel_recursive &sipStrings_PyKDL[29]
#define sipNameNr_ChainFkSolverPos_recursive 56
#define sipName_ChainFkSolverPos_recursive &sipStrings_PyKDL[56]
#define sipNameNr_ChainIkSolverVel_pinv_nso 83
#define sipName_ChainIkSolverVel_pinv_nso &sipStrings_PyKDL[83]
#define sipNameNr_ChainIkSolverPos_NR_JL 109
#define sipName_ChainIkSolverPos_NR_JL &sipStrings_PyKDL[109]
#define sipNameNr_JntSpaceInertiaMatrix 132
#define sipName_JntSpaceInertiaMatrix &sipStrings_PyKDL[132]
#define sipNameNr_ChainIkSolverVel_wdls 154
#define sipName_ChainIkSolverVel_wdls &sipStrings_PyKDL[154]
#define sipNameNr_ChainIkSolverVel_pinv 176
#define sipName_ChainIkSolverVel_pinv &sipStrings_PyKDL[176]
#define sipNameNr_ChainIkSolverPos_LMA 198
#define sipName_ChainIkSolverPos_LMA &sipStrings_PyKDL[198]
#define sipNameNr_getRotationalInertia 219
#define sipName_getRotationalInertia &sipStrings_PyKDL[219]
#define sipNameNr_ChainJntToJacSolver 240
#define sipName_ChainJntToJacSolver &sipStrings_PyKDL[240]
#define sipNameNr_ChainIkSolverPos_NR 260
#define sipName_ChainIkSolverPos_NR &sipStrings_PyKDL[260]
#define sipNameNr_RotationalInertia 222
#define sipName_RotationalInertia &sipStrings_PyKDL[222]
#define sipNameNr_ChainIkSolverVel 280
#define sipName_ChainIkSolverVel &sipStrings_PyKDL[280]
#define sipNameNr_ChainIkSolverPos 297
#define sipName_ChainIkSolverPos &sipStrings_PyKDL[297]
#define sipNameNr_ChainFkSolverVel 314
#define sipName_ChainFkSolverVel &sipStrings_PyKDL[314]
#define sipNameNr_ChainFkSolverPos 331
#define sipName_ChainFkSolverPos &sipStrings_PyKDL[331]
#define sipNameNr_MultiplyJacobian 348
#define sipName_MultiplyJacobian &sipStrings_PyKDL[348]
#define sipNameNr_RigidBodyInertia 365
#define sipName_RigidBodyInertia &sipStrings_PyKDL[365]
#define sipNameNr_Joint__JointType 382
#define sipName_Joint__JointType &sipStrings_PyKDL[382]
#define sipNameNr_getNrOfSegments 399
#define sipName_getNrOfSegments &sipStrings_PyKDL[399]
#define sipNameNr_changeRefFrame 415
#define sipName_changeRefFrame &sipStrings_PyKDL[415]
#define sipNameNr_changeRefPoint 430
#define sipName_changeRefPoint &sipStrings_PyKDL[430]
#define sipNameNr_JntToCoriolis 445
#define sipName_JntToCoriolis &sipStrings_PyKDL[445]
#define sipNameNr_ChainDynParam 459
#define sipName_ChainDynParam &sipStrings_PyKDL[459]
#define sipNameNr_getNrOfJoints 473
#define sipName_getNrOfJoints &sipStrings_PyKDL[473]
#define sipNameNr_getFrameToTip 487
#define sipName_getFrameToTip &sipStrings_PyKDL[487]
#define sipNameNr_GetQuaternion 501
#define sipName_GetQuaternion &sipStrings_PyKDL[501]
#define sipNameNr_JntToGravity 515
#define sipName_JntToGravity &sipStrings_PyKDL[515]
#define sipNameNr_DH_Craig1989 528
#define sipName_DH_Craig1989 &sipStrings_PyKDL[528]
#define sipNameNr_GetTwistDot 541
#define sipName_GetTwistDot &sipStrings_PyKDL[541]
#define sipNameNr_RotationVel 553
#define sipName_RotationVel &sipStrings_PyKDL[553]
#define sipNameNr_setWeightJS 565
#define sipName_setWeightJS &sipStrings_PyKDL[565]
#define sipNameNr_setWeightTS 577
#define sipName_setWeightTS &sipStrings_PyKDL[577]
#define sipNameNr_JntArrayVel 589
#define sipName_JntArrayVel &sipStrings_PyKDL[589]
#define sipNameNr_getTypeName 601
#define sipName_getTypeName &sipStrings_PyKDL[601]
#define sipNameNr_JointOrigin 613
#define sipName_JointOrigin &sipStrings_PyKDL[613]
#define sipNameNr_GetEulerZYX 625
#define sipName_GetEulerZYX &sipStrings_PyKDL[625]
#define sipNameNr_GetEulerZYZ 637
#define sipName_GetEulerZYZ &sipStrings_PyKDL[637]
#define sipNameNr_GetRotAngle 649
#define sipName_GetRotAngle &sipStrings_PyKDL[649]
#define sipNameNr_ReverseSign 661
#define sipName_ReverseSign &sipStrings_PyKDL[661]
#define sipNameNr___setitem__ 673
#define sipName___setitem__ &sipStrings_PyKDL[673]
#define sipNameNr___getitem__ 685
#define sipName___getitem__ &sipStrings_PyKDL[685]
#define sipNameNr_std__string 697
#define sipName_std__string &sipStrings_PyKDL[697]
#define sipNameNr_changeBase 709
#define sipName_changeBase &sipStrings_PyKDL[709]
#define sipNameNr_getSegment 720
#define sipName_getSegment &sipStrings_PyKDL[720]
#define sipNameNr_addSegment 731
#define sipName_addSegment &sipStrings_PyKDL[731]
#define sipNameNr_setInertia 742
#define sipName_setInertia &sipStrings_PyKDL[742]
#define sipNameNr_getInertia 753
#define sipName_getInertia &sipStrings_PyKDL[753]
#define sipNameNr_Quaternion 504
#define sipName_Quaternion &sipStrings_PyKDL[504]
#define sipNameNr_SetInverse 764
#define sipName_SetInverse &sipStrings_PyKDL[764]
#define sipNameNr_JntToMass 775
#define sipName_JntToMass &sipStrings_PyKDL[775]
#define sipNameNr_VectorVel 785
#define sipName_VectorVel &sipStrings_PyKDL[785]
#define sipNameNr_doubleVel 795
#define sipName_doubleVel &sipStrings_PyKDL[795]
#define sipNameNr_setLambda 805
#define sipName_setLambda &sipStrings_PyKDL[805]
#define sipNameNr_CartToJnt 815
#define sipName_CartToJnt &sipStrings_PyKDL[815]
#define sipNameNr_JntToCart 825
#define sipName_JntToCart &sipStrings_PyKDL[825]
#define sipNameNr_setColumn 835
#define sipName_setColumn &sipStrings_PyKDL[835]
#define sipNameNr_getColumn 845
#define sipName_getColumn &sipStrings_PyKDL[845]
#define sipNameNr_JointAxis 855
#define sipName_JointAxis &sipStrings_PyKDL[855]
#define sipNameNr_TransAxis 865
#define sipName_TransAxis &sipStrings_PyKDL[865]
#define sipNameNr_JointType 389
#define sipName_JointType &sipStrings_PyKDL[389]
#define sipNameNr_Integrate 875
#define sipName_Integrate &sipStrings_PyKDL[875]
#define sipNameNr_SetToZero 885
#define sipName_SetToZero &sipStrings_PyKDL[885]
#define sipNameNr_Normalize 895
#define sipName_Normalize &sipStrings_PyKDL[895]
#define sipNameNr_TwistVel 905
#define sipName_TwistVel &sipStrings_PyKDL[905]
#define sipNameNr_GetTwist 914
#define sipName_GetTwist &sipStrings_PyKDL[914]
#define sipNameNr_GetFrame 923
#define sipName_GetFrame &sipStrings_PyKDL[923]
#define sipNameNr_FrameVel 932
#define sipName_FrameVel &sipStrings_PyKDL[932]
#define sipNameNr_JntToJac 941
#define sipName_JntToJac &sipStrings_PyKDL[941]
#define sipNameNr_Jacobian 356
#define sipName_Jacobian &sipStrings_PyKDL[356]
#define sipNameNr_Multiply 950
#define sipName_Multiply &sipStrings_PyKDL[950]
#define sipNameNr_Subtract 959
#define sipName_Subtract &sipStrings_PyKDL[959]
#define sipNameNr_JntArray 968
#define sipName_JntArray &sipStrings_PyKDL[968]
#define sipNameNr_getChain 977
#define sipName_getChain &sipStrings_PyKDL[977]
#define sipNameNr_addChain 986
#define sipName_addChain &sipStrings_PyKDL[986]
#define sipNameNr_getJoint 995
#define sipName_getJoint &sipStrings_PyKDL[995]
#define sipNameNr_addDelta 1004
#define sipName_addDelta &sipStrings_PyKDL[1004]
#define sipNameNr_RefPoint 436
#define sipName_RefPoint &sipStrings_PyKDL[436]
#define sipNameNr_EulerZYX 628
#define sipName_EulerZYX &sipStrings_PyKDL[628]
#define sipNameNr_EulerZYZ 640
#define sipName_EulerZYZ &sipStrings_PyKDL[640]
#define sipNameNr_Identity 1013
#define sipName_Identity &sipStrings_PyKDL[1013]
#define sipNameNr_Rotation 1022
#define sipName_Rotation &sipStrings_PyKDL[1022]
#define sipNameNr___iadd__ 1031
#define sipName___iadd__ &sipStrings_PyKDL[1031]
#define sipNameNr___isub__ 1040
#define sipName___isub__ &sipStrings_PyKDL[1040]
#define sipNameNr___repr__ 1049
#define sipName___repr__ &sipStrings_PyKDL[1049]
#define sipNameNr_columns 1058
#define sipName_columns &sipStrings_PyKDL[1058]
#define sipNameNr_Segment 723
#define sipName_Segment &sipStrings_PyKDL[723]
#define sipNameNr_getMass 1066
#define sipName_getMass &sipStrings_PyKDL[1066]
#define sipNameNr_getType 1074
#define sipName_getType &sipStrings_PyKDL[1074]
#define sipNameNr_getName 1082
#define sipName_getName &sipStrings_PyKDL[1082]
#define sipNameNr_RotAxis 1090
#define sipName_RotAxis &sipStrings_PyKDL[1090]
#define sipNameNr_Inverse 767
#define sipName_Inverse &sipStrings_PyKDL[767]
#define sipNameNr___sub__ 1098
#define sipName___sub__ &sipStrings_PyKDL[1098]
#define sipNameNr___add__ 1106
#define sipName___add__ &sipStrings_PyKDL[1106]
#define sipNameNr___div__ 1114
#define sipName___div__ &sipStrings_PyKDL[1114]
#define sipNameNr___mul__ 1122
#define sipName___mul__ &sipStrings_PyKDL[1122]
#define sipNameNr___neg__ 1130
#define sipName___neg__ &sipStrings_PyKDL[1130]
#define sipNameNr_Divide 1138
#define sipName_Divide &sipStrings_PyKDL[1138]
#define sipNameNr_resize 1145
#define sipName_resize &sipStrings_PyKDL[1145]
#define sipNameNr_getCOG 1152
#define sipName_getCOG &sipStrings_PyKDL[1152]
#define sipNameNr_TransZ 1159
#define sipName_TransZ &sipStrings_PyKDL[1159]
#define sipNameNr_TransY 1166
#define sipName_TransY &sipStrings_PyKDL[1166]
#define sipNameNr_TransX 1173
#define sipName_TransX &sipStrings_PyKDL[1173]
#define sipNameNr_torque 1180
#define sipName_torque &sipStrings_PyKDL[1180]
#define sipNameNr_Wrench 1187
#define sipName_Wrench &sipStrings_PyKDL[1187]
#define sipNameNr_GetRPY 1194
#define sipName_GetRPY &sipStrings_PyKDL[1194]
#define sipNameNr_GetRot 1201
#define sipName_GetRot &sipStrings_PyKDL[1201]
#define sipNameNr_DoRotZ 1208
#define sipName_DoRotZ &sipStrings_PyKDL[1208]
#define sipNameNr_DoRotY 1215
#define sipName_DoRotY &sipStrings_PyKDL[1215]
#define sipNameNr_DoRotX 1222
#define sipName_DoRotX &sipStrings_PyKDL[1222]
#define sipNameNr___ne__ 1229
#define sipName___ne__ &sipStrings_PyKDL[1229]
#define sipNameNr___eq__ 1236
#define sipName___eq__ &sipStrings_PyKDL[1236]
#define sipNameNr_Vector 1243
#define sipName_Vector &sipStrings_PyKDL[1243]
#define sipNameNr_string 702
#define sipName_string &sipStrings_PyKDL[702]
#define sipNameNr_deriv 1250
#define sipName_deriv &sipStrings_PyKDL[1250]
#define sipNameNr_Chain 980
#define sipName_Chain &sipStrings_PyKDL[980]
#define sipNameNr_twist 1256
#define sipName_twist &sipStrings_PyKDL[1256]
#define sipNameNr_Joint 998
#define sipName_Joint &sipStrings_PyKDL[998]
#define sipNameNr_force 1262
#define sipName_force &sipStrings_PyKDL[1262]
#define sipNameNr_Twist 917
#define sipName_Twist &sipStrings_PyKDL[917]
#define sipNameNr_Frame 424
#define sipName_Frame &sipStrings_PyKDL[424]
#define sipNameNr_UnitZ 1268
#define sipName_UnitZ &sipStrings_PyKDL[1268]
#define sipNameNr_UnitY 1274
#define sipName_UnitY &sipStrings_PyKDL[1274]
#define sipNameNr_UnitX 1280
#define sipName_UnitX &sipStrings_PyKDL[1280]
#define sipNameNr_Equal 1286
#define sipName_Equal &sipStrings_PyKDL[1286]
#define sipNameNr_value 1292
#define sipName_value &sipStrings_PyKDL[1292]
#define sipNameNr_PyKDL 1298
#define sipName_PyKDL &sipStrings_PyKDL[1298]
#define sipNameNr_grad 1304
#define sipName_grad &sipStrings_PyKDL[1304]
#define sipNameNr_rows 1309
#define sipName_rows &sipStrings_PyKDL[1309]
#define sipNameNr_Tree 1314
#define sipName_Tree &sipStrings_PyKDL[1314]
#define sipNameNr_qdot 1319
#define sipName_qdot &sipStrings_PyKDL[1319]
#define sipNameNr_pose 1324
#define sipName_pose &sipStrings_PyKDL[1324]
#define sipNameNr_None 1329
#define sipName_None &sipStrings_PyKDL[1329]
#define sipNameNr_diff 1334
#define sipName_diff &sipStrings_PyKDL[1334]
#define sipNameNr_Rot2 1339
#define sipName_Rot2 &sipStrings_PyKDL[1339]
#define sipNameNr_RotZ 1210
#define sipName_RotZ &sipStrings_PyKDL[1210]
#define sipNameNr_RotY 1217
#define sipName_RotY &sipStrings_PyKDL[1217]
#define sipNameNr_RotX 1224
#define sipName_RotX &sipStrings_PyKDL[1224]
#define sipNameNr_Norm 1344
#define sipName_Norm &sipStrings_PyKDL[1344]
#define sipNameNr_Zero 890
#define sipName_Zero &sipStrings_PyKDL[890]
#define sipNameNr_Add 1349
#define sipName_Add &sipStrings_PyKDL[1349]
#define sipNameNr_rot 1353
#define sipName_rot &sipStrings_PyKDL[1353]
#define sipNameNr_vel 1357
#define sipName_vel &sipStrings_PyKDL[1357]
#define sipNameNr_RPY 1197
#define sipName_RPY &sipStrings_PyKDL[1197]
#define sipNameNr_Rot 1204
#define sipName_Rot &sipStrings_PyKDL[1204]
#define sipNameNr_dot 1320
#define sipName_dot &sipStrings_PyKDL[1320]
#define sipNameNr_DH 1361
#define sipName_DH &sipStrings_PyKDL[1361]
#define sipNameNr_q 1364
#define sipName_q &sipStrings_PyKDL[1364]
#define sipNameNr_M 1366
#define sipName_M &sipStrings_PyKDL[1366]
#define sipNameNr_p 499
#define sipName_p &sipStrings_PyKDL[499]
#define sipNameNr_R 278
#define sipName_R &sipStrings_PyKDL[278]
#define sipNameNr_t 443
#define sipName_t &sipStrings_PyKDL[443]
#define sipNameNr_w 1368
#define sipName_w &sipStrings_PyKDL[1368]
#define sipNameNr_v 196
#define sipName_v &sipStrings_PyKDL[196]
#define sipNameNr_z 1370
#define sipName_z &sipStrings_PyKDL[1370]
#define sipNameNr_y 526
#define sipName_y &sipStrings_PyKDL[526]
#define sipNameNr_x 152
#define sipName_x &sipStrings_PyKDL[152]

#define sipMalloc                   sipAPI_PyKDL->api_malloc
#define sipFree                     sipAPI_PyKDL->api_free
#define sipBuildResult              sipAPI_PyKDL->api_build_result
#define sipCallMethod               sipAPI_PyKDL->api_call_method
#define sipCallErrorHandler         sipAPI_PyKDL->api_call_error_handler
#define sipParseResultEx            sipAPI_PyKDL->api_parse_result_ex
#define sipParseResult              sipAPI_PyKDL->api_parse_result
#define sipParseArgs                sipAPI_PyKDL->api_parse_args
#define sipParseKwdArgs             sipAPI_PyKDL->api_parse_kwd_args
#define sipParsePair                sipAPI_PyKDL->api_parse_pair
#define sipCommonDtor               sipAPI_PyKDL->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_PyKDL->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_PyKDL->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_PyKDL->api_convert_to_void_ptr
#define sipAddException             sipAPI_PyKDL->api_add_exception
#define sipNoFunction               sipAPI_PyKDL->api_no_function
#define sipNoMethod                 sipAPI_PyKDL->api_no_method
#define sipAbstractMethod           sipAPI_PyKDL->api_abstract_method
#define sipBadClass                 sipAPI_PyKDL->api_bad_class
#define sipBadCatcherResult         sipAPI_PyKDL->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_PyKDL->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_PyKDL->api_bad_operator_arg
#define sipTrace                    sipAPI_PyKDL->api_trace
#define sipTransferBack             sipAPI_PyKDL->api_transfer_back
#define sipTransferTo               sipAPI_PyKDL->api_transfer_to
#define sipTransferBreak            sipAPI_PyKDL->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_PyKDL->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_PyKDL->api_wrapper_type
#define sipWrapperType_Type         sipAPI_PyKDL->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_PyKDL->api_voidptr_type
#define sipGetPyObject              sipAPI_PyKDL->api_get_pyobject
#define sipGetAddress               sipAPI_PyKDL->api_get_address
#define sipGetMixinAddress          sipAPI_PyKDL->api_get_mixin_address
#define sipGetCppPtr                sipAPI_PyKDL->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_PyKDL->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_PyKDL->api_is_py_method
#define sipCallHook                 sipAPI_PyKDL->api_call_hook
#define sipEndThread                sipAPI_PyKDL->api_end_thread
#define sipConnectRx                sipAPI_PyKDL->api_connect_rx
#define sipDisconnectRx             sipAPI_PyKDL->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_PyKDL->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_PyKDL->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_PyKDL->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_PyKDL->api_add_type_instance
#define sipFreeSipslot              sipAPI_PyKDL->api_free_sipslot
#define sipSameSlot                 sipAPI_PyKDL->api_same_slot
#define sipPySlotExtend             sipAPI_PyKDL->api_pyslot_extend
#define sipConvertRx                sipAPI_PyKDL->api_convert_rx
#define sipAddDelayedDtor           sipAPI_PyKDL->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_PyKDL->api_can_convert_to_type
#define sipConvertToType            sipAPI_PyKDL->api_convert_to_type
#define sipForceConvertToType       sipAPI_PyKDL->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_PyKDL->api_can_convert_to_enum
#define sipReleaseType              sipAPI_PyKDL->api_release_type
#define sipConvertFromType          sipAPI_PyKDL->api_convert_from_type
#define sipConvertFromNewType       sipAPI_PyKDL->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_PyKDL->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_PyKDL->api_convert_from_enum
#define sipGetState                 sipAPI_PyKDL->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_PyKDL->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_PyKDL->api_export_symbol
#define sipImportSymbol             sipAPI_PyKDL->api_import_symbol
#define sipFindType                 sipAPI_PyKDL->api_find_type
#define sipFindNamedEnum            sipAPI_PyKDL->api_find_named_enum
#define sipBytes_AsChar             sipAPI_PyKDL->api_bytes_as_char
#define sipBytes_AsString           sipAPI_PyKDL->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_PyKDL->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_PyKDL->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_PyKDL->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_PyKDL->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_PyKDL->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_PyKDL->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_PyKDL->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_PyKDL->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_PyKDL->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_PyKDL->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_PyKDL->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_PyKDL->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_PyKDL->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_PyKDL->api_save_slot
#define sipClearAnySlotReference    sipAPI_PyKDL->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_PyKDL->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_PyKDL->api_deprecated
#define sipGetReference             sipAPI_PyKDL->api_get_reference
#define sipKeepReference            sipAPI_PyKDL->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_PyKDL->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_PyKDL->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_PyKDL->api_type_from_py_type_object
#define sipTypeScope                sipAPI_PyKDL->api_type_scope
#define sipResolveTypedef           sipAPI_PyKDL->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_PyKDL->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_PyKDL->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_PyKDL->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_PyKDL->api_enable_autoconversion
#define sipInitMixin                sipAPI_PyKDL->api_init_mixin
#define sipExportModule             sipAPI_PyKDL->api_export_module
#define sipInitModule               sipAPI_PyKDL->api_init_module

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_PyKDL->api_map_string_to_class
#define sipMapIntToClass            sipAPI_PyKDL->api_map_int_to_class
#define sipFindClass                sipAPI_PyKDL->api_find_class
#define sipFindMappedType           sipAPI_PyKDL->api_find_mapped_type
#define sipConvertToArray           sipAPI_PyKDL->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_PyKDL->api_convert_to_typed_array
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_PyKDL->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_PyKDL[];

#define sipType_Vector              sipModuleAPI_PyKDL.em_types[32]
#define sipClass_Vector             sipModuleAPI_PyKDL.em_types[32]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Vector;

#define sipType_Rotation              sipModuleAPI_PyKDL.em_types[25]
#define sipClass_Rotation             sipModuleAPI_PyKDL.em_types[25]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Rotation;

#define sipType_Frame              sipModuleAPI_PyKDL.em_types[16]
#define sipClass_Frame             sipModuleAPI_PyKDL.em_types[16]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Frame;

#define sipType_Twist              sipModuleAPI_PyKDL.em_types[30]
#define sipClass_Twist             sipModuleAPI_PyKDL.em_types[30]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Twist;

#define sipType_Wrench              sipModuleAPI_PyKDL.em_types[34]
#define sipClass_Wrench             sipModuleAPI_PyKDL.em_types[34]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Wrench;

#define sipType_Joint              sipModuleAPI_PyKDL.em_types[22]
#define sipClass_Joint             sipModuleAPI_PyKDL.em_types[22]->u.td_wrapper_type

#define sipType_Joint_JointType              sipModuleAPI_PyKDL.em_types[23]
#define sipEnum_Joint_JointType              sipModuleAPI_PyKDL.em_types[23]->u.td_py_type

extern sipClassTypeDef sipTypeDef_PyKDL_Joint;

#define sipType_RotationalInertia              sipModuleAPI_PyKDL.em_types[27]
#define sipClass_RotationalInertia             sipModuleAPI_PyKDL.em_types[27]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_RotationalInertia;

#define sipType_RigidBodyInertia              sipModuleAPI_PyKDL.em_types[24]
#define sipClass_RigidBodyInertia             sipModuleAPI_PyKDL.em_types[24]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_RigidBodyInertia;

#define sipType_Segment              sipModuleAPI_PyKDL.em_types[28]
#define sipClass_Segment             sipModuleAPI_PyKDL.em_types[28]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Segment;

#define sipType_Chain              sipModuleAPI_PyKDL.em_types[0]
#define sipClass_Chain             sipModuleAPI_PyKDL.em_types[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Chain;

#define sipType_Tree              sipModuleAPI_PyKDL.em_types[29]
#define sipClass_Tree             sipModuleAPI_PyKDL.em_types[29]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Tree;

#define sipType_JntArray              sipModuleAPI_PyKDL.em_types[19]
#define sipClass_JntArray             sipModuleAPI_PyKDL.em_types[19]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_JntArray;

#define sipType_JntArrayVel              sipModuleAPI_PyKDL.em_types[20]
#define sipClass_JntArrayVel             sipModuleAPI_PyKDL.em_types[20]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_JntArrayVel;

#define sipType_Jacobian              sipModuleAPI_PyKDL.em_types[18]
#define sipClass_Jacobian             sipModuleAPI_PyKDL.em_types[18]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_Jacobian;

#define sipType_ChainFkSolverPos              sipModuleAPI_PyKDL.em_types[2]
#define sipClass_ChainFkSolverPos             sipModuleAPI_PyKDL.em_types[2]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainFkSolverPos;

#define sipType_ChainFkSolverVel              sipModuleAPI_PyKDL.em_types[4]
#define sipClass_ChainFkSolverVel             sipModuleAPI_PyKDL.em_types[4]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainFkSolverVel;

#define sipType_ChainFkSolverPos_recursive              sipModuleAPI_PyKDL.em_types[3]
#define sipClass_ChainFkSolverPos_recursive             sipModuleAPI_PyKDL.em_types[3]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainFkSolverPos_recursive;

#define sipType_ChainFkSolverVel_recursive              sipModuleAPI_PyKDL.em_types[5]
#define sipClass_ChainFkSolverVel_recursive             sipModuleAPI_PyKDL.em_types[5]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainFkSolverVel_recursive;

#define sipType_ChainIkSolverPos              sipModuleAPI_PyKDL.em_types[6]
#define sipClass_ChainIkSolverPos             sipModuleAPI_PyKDL.em_types[6]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverPos;

#define sipType_ChainIkSolverVel              sipModuleAPI_PyKDL.em_types[10]
#define sipClass_ChainIkSolverVel             sipModuleAPI_PyKDL.em_types[10]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverVel;

#define sipType_ChainIkSolverPos_NR              sipModuleAPI_PyKDL.em_types[8]
#define sipClass_ChainIkSolverPos_NR             sipModuleAPI_PyKDL.em_types[8]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverPos_NR;

#define sipType_ChainIkSolverPos_NR_JL              sipModuleAPI_PyKDL.em_types[9]
#define sipClass_ChainIkSolverPos_NR_JL             sipModuleAPI_PyKDL.em_types[9]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverPos_NR_JL;

#define sipType_ChainIkSolverVel_pinv              sipModuleAPI_PyKDL.em_types[11]
#define sipClass_ChainIkSolverVel_pinv             sipModuleAPI_PyKDL.em_types[11]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverVel_pinv;

#define sipType_ChainIkSolverVel_wdls              sipModuleAPI_PyKDL.em_types[14]
#define sipClass_ChainIkSolverVel_wdls             sipModuleAPI_PyKDL.em_types[14]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverVel_wdls;

#define sipType_ChainIkSolverPos_LMA              sipModuleAPI_PyKDL.em_types[7]
#define sipClass_ChainIkSolverPos_LMA             sipModuleAPI_PyKDL.em_types[7]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverPos_LMA;

#define sipType_ChainIkSolverVel_pinv_nso              sipModuleAPI_PyKDL.em_types[13]
#define sipClass_ChainIkSolverVel_pinv_nso             sipModuleAPI_PyKDL.em_types[13]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverVel_pinv_nso;

#define sipType_ChainIkSolverVel_pinv_givens              sipModuleAPI_PyKDL.em_types[12]
#define sipClass_ChainIkSolverVel_pinv_givens             sipModuleAPI_PyKDL.em_types[12]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainIkSolverVel_pinv_givens;

#define sipType_ChainJntToJacSolver              sipModuleAPI_PyKDL.em_types[15]
#define sipClass_ChainJntToJacSolver             sipModuleAPI_PyKDL.em_types[15]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainJntToJacSolver;

#define sipType_doubleVel              sipModuleAPI_PyKDL.em_types[35]
#define sipClass_doubleVel             sipModuleAPI_PyKDL.em_types[35]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_doubleVel;

#define sipType_VectorVel              sipModuleAPI_PyKDL.em_types[33]
#define sipClass_VectorVel             sipModuleAPI_PyKDL.em_types[33]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_VectorVel;

#define sipType_RotationVel              sipModuleAPI_PyKDL.em_types[26]
#define sipClass_RotationVel             sipModuleAPI_PyKDL.em_types[26]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_RotationVel;

#define sipType_FrameVel              sipModuleAPI_PyKDL.em_types[17]
#define sipClass_FrameVel             sipModuleAPI_PyKDL.em_types[17]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_FrameVel;

#define sipType_TwistVel              sipModuleAPI_PyKDL.em_types[31]
#define sipClass_TwistVel             sipModuleAPI_PyKDL.em_types[31]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_TwistVel;

#define sipType_JntSpaceInertiaMatrix              sipModuleAPI_PyKDL.em_types[21]
#define sipClass_JntSpaceInertiaMatrix             sipModuleAPI_PyKDL.em_types[21]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_JntSpaceInertiaMatrix;

#define sipType_ChainDynParam              sipModuleAPI_PyKDL.em_types[1]
#define sipClass_ChainDynParam             sipModuleAPI_PyKDL.em_types[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_PyKDL_ChainDynParam;

#define sipType_std_string      sipModuleAPI_PyKDL.em_types[36]

extern sipMappedTypeDef sipTypeDef_PyKDL_std_string;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_PyKDL;
extern sipExportedModuleDef sipModuleAPI_PyKDL;

#endif
