set(_CATKIN_CURRENT_PACKAGE "rqt_msg")
set(rqt_msg_VERSION "0.3.13")
set(rqt_msg_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_msg_PACKAGE_FORMAT "1")
set(rqt_msg_BUILD_DEPENDS )
set(rqt_msg_BUILD_EXPORT_DEPENDS "python-rospkg" "roslib" "rosmsg" "rospy" "rqt_gui" "rqt_gui_py" "rqt_py_common" "rqt_console")
set(rqt_msg_BUILDTOOL_DEPENDS "catkin")
set(rqt_msg_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_msg_EXEC_DEPENDS "python-rospkg" "roslib" "rosmsg" "rospy" "rqt_gui" "rqt_gui_py" "rqt_py_common" "rqt_console")
set(rqt_msg_RUN_DEPENDS "python-rospkg" "roslib" "rosmsg" "rospy" "rqt_gui" "rqt_gui_py" "rqt_py_common" "rqt_console")
set(rqt_msg_TEST_DEPENDS )
set(rqt_msg_DOC_DEPENDS )
set(rqt_msg_DEPRECATED "")