set(_CATKIN_CURRENT_PACKAGE "nodelet_tutorial_math")
set(nodelet_tutorial_math_VERSION "0.1.8")
set(nodelet_tutorial_math_MAINTAINER "Daniel Stonier <d.stonier@gmail.com>")
set(nodelet_tutorial_math_PACKAGE_FORMAT "1")
set(nodelet_tutorial_math_BUILD_DEPENDS "nodelet" "roscpp" "std_msgs")
set(nodelet_tutorial_math_BUILD_EXPORT_DEPENDS "nodelet" "roscpp" "std_msgs")
set(nodelet_tutorial_math_BUILDTOOL_DEPENDS "catkin")
set(nodelet_tutorial_math_BUILDTOOL_EXPORT_DEPENDS )
set(nodelet_tutorial_math_EXEC_DEPENDS "nodelet" "roscpp" "std_msgs")
set(nodelet_tutorial_math_RUN_DEPENDS "nodelet" "roscpp" "std_msgs")
set(nodelet_tutorial_math_TEST_DEPENDS )
set(nodelet_tutorial_math_DOC_DEPENDS )
set(nodelet_tutorial_math_DEPRECATED "")