set(_CATKIN_CURRENT_PACKAGE "nodelet_core")
set(nodelet_core_VERSION "1.9.4")
set(nodelet_core_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(nodelet_core_PACKAGE_FORMAT "1")
set(nodelet_core_BUILD_DEPENDS )
set(nodelet_core_BUILD_EXPORT_DEPENDS "nodelet" "nodelet_topic_tools")
set(nodelet_core_BUILDTOOL_DEPENDS "catkin")
set(nodelet_core_BUILDTOOL_EXPORT_DEPENDS )
set(nodelet_core_EXEC_DEPENDS "nodelet" "nodelet_topic_tools")
set(nodelet_core_RUN_DEPENDS "nodelet" "nodelet_topic_tools")
set(nodelet_core_TEST_DEPENDS )
set(nodelet_core_DOC_DEPENDS )
set(nodelet_core_DEPRECATED "")