set(rqt_bag_SETUP_PY_VERSION "0.3.13")
set(rqt_bag_SETUP_PY_SCRIPTS "scripts/rqt_bag")
set(rqt_bag_SETUP_PY_PACKAGES "rqt_bag")
set(rqt_bag_SETUP_PY_PACKAGE_DIRS "src/rqt_bag")
set(rqt_bag_SETUP_PY_MODULES "")
set(rqt_bag_SETUP_PY_MODULE_DIRS "")