set(_CATKIN_CURRENT_PACKAGE "roscreate")
set(roscreate_VERSION "1.12.7")
set(roscreate_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(roscreate_PACKAGE_FORMAT "1")
set(roscreate_BUILD_DEPENDS )
set(roscreate_BUILD_EXPORT_DEPENDS "python-rospkg")
set(roscreate_BUILDTOOL_DEPENDS "catkin")
set(roscreate_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(roscreate_BUILDTOOL_EXPORT_DEPENDS )
set(roscreate_EXEC_DEPENDS "python-rospkg")
set(roscreate_RUN_DEPENDS "python-rospkg")
set(roscreate_TEST_DEPENDS )
set(roscreate_DOC_DEPENDS )
set(roscreate_DEPRECATED "")