set(roscreate_SETUP_PY_VERSION "1.12.7")
set(roscreate_SETUP_PY_SCRIPTS "scripts/roscreate-pkg")
set(roscreate_SETUP_PY_PACKAGES "roscreate")
set(roscreate_SETUP_PY_PACKAGE_DIRS "src/roscreate")
set(roscreate_SETUP_PY_MODULES "")
set(roscreate_SETUP_PY_MODULE_DIRS "")