set(_CATKIN_CURRENT_PACKAGE "gencpp")
set(gencpp_VERSION "0.5.4")
set(gencpp_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(gencpp_PACKAGE_FORMAT "1")
set(gencpp_BUILD_DEPENDS "genmsg")
set(gencpp_BUILD_EXPORT_DEPENDS "genmsg")
set(gencpp_BUILDTOOL_DEPENDS "catkin")
set(gencpp_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(gencpp_BUILDTOOL_EXPORT_DEPENDS )
set(gencpp_EXEC_DEPENDS "genmsg")
set(gencpp_RUN_DEPENDS "genmsg")
set(gencpp_TEST_DEPENDS )
set(gencpp_DOC_DEPENDS )
set(gencpp_DEPRECATED "")