set(gencpp_SETUP_PY_VERSION "0.5.4")
set(gencpp_SETUP_PY_SCRIPTS "")
set(gencpp_SETUP_PY_PACKAGES "gencpp")
set(gencpp_SETUP_PY_PACKAGE_DIRS "src/gencpp")
set(gencpp_SETUP_PY_MODULES "")
set(gencpp_SETUP_PY_MODULE_DIRS "")