# CMake generated Testfile for 
# Source directory: /opt/ros_catkin_ws/src/ros_comm/rostest
# Build directory: /opt/ros_catkin_ws/build_isolated/rostest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rostest_gtest_test_permuter "/opt/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rostest/test_results/rostest/gtest-test_permuter.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/rostest/lib/rostest/test_permuter --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/rostest/test_results/rostest/gtest-test_permuter.xml")
add_test(_ctest_rostest_rostest_test_hztest0.test "/opt/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_hztest0.xml" "--return-code" "/opt/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_hztest0.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rostest/test_results\" /opt/ros_catkin_ws/src/ros_comm/rostest/test/hztest0.test ")
add_test(_ctest_rostest_rostest_test_hztest.test "/opt/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_hztest.xml" "--return-code" "/opt/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_hztest.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rostest/test_results\" /opt/ros_catkin_ws/src/ros_comm/rostest/test/hztest.test ")
add_test(_ctest_rostest_rostest_test_clean_master.test "/opt/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_clean_master.xml" "--return-code" "/opt/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_clean_master.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rostest/test_results\" /opt/ros_catkin_ws/src/ros_comm/rostest/test/clean_master.test ")
add_test(_ctest_rostest_rostest_test_distro_version.test "/opt/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_distro_version.xml" "--return-code" "/opt/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/opt/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_distro_version.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/rostest/test_results\" /opt/ros_catkin_ws/src/ros_comm/rostest/test/distro_version.test ")
subdirs(gtest)
