set(_CATKIN_CURRENT_PACKAGE "qt_gui_py_common")
set(qt_gui_py_common_VERSION "0.2.30")
set(qt_gui_py_common_MAINTAINER "Dorian Scholz <scholz@sim.tu-darmstadt.de>")
set(qt_gui_py_common_PACKAGE_FORMAT "1")
set(qt_gui_py_common_BUILD_DEPENDS )
set(qt_gui_py_common_BUILD_EXPORT_DEPENDS "python_qt_binding" "python-rospkg")
set(qt_gui_py_common_BUILDTOOL_DEPENDS "catkin")
set(qt_gui_py_common_BUILDTOOL_EXPORT_DEPENDS )
set(qt_gui_py_common_EXEC_DEPENDS "python_qt_binding" "python-rospkg")
set(qt_gui_py_common_RUN_DEPENDS "python_qt_binding" "python-rospkg")
set(qt_gui_py_common_TEST_DEPENDS )
set(qt_gui_py_common_DOC_DEPENDS )
set(qt_gui_py_common_DEPRECATED "")