set(qt_gui_py_common_SETUP_PY_VERSION "0.2.30")
set(qt_gui_py_common_SETUP_PY_SCRIPTS "")
set(qt_gui_py_common_SETUP_PY_PACKAGES "qt_gui_py_common")
set(qt_gui_py_common_SETUP_PY_PACKAGE_DIRS "src/qt_gui_py_common")
set(qt_gui_py_common_SETUP_PY_MODULES "")
set(qt_gui_py_common_SETUP_PY_MODULE_DIRS "")