set(_CATKIN_CURRENT_PACKAGE "rqt_image_view")
set(rqt_image_view_VERSION "0.3.13")
set(rqt_image_view_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_image_view_PACKAGE_FORMAT "1")
set(rqt_image_view_BUILD_DEPENDS "cv_bridge" "image_transport" "rqt_gui" "rqt_gui_cpp" "sensor_msgs")
set(rqt_image_view_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "rqt_gui" "rqt_gui_cpp" "sensor_msgs")
set(rqt_image_view_BUILDTOOL_DEPENDS "catkin")
set(rqt_image_view_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_image_view_EXEC_DEPENDS "cv_bridge" "image_transport" "rqt_gui" "rqt_gui_cpp" "sensor_msgs")
set(rqt_image_view_RUN_DEPENDS "cv_bridge" "image_transport" "rqt_gui" "rqt_gui_cpp" "sensor_msgs")
set(rqt_image_view_TEST_DEPENDS )
set(rqt_image_view_DOC_DEPENDS )
set(rqt_image_view_DEPRECATED "")