set(_CATKIN_CURRENT_PACKAGE "common_msgs")
set(common_msgs_VERSION "1.12.4")
set(common_msgs_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(common_msgs_PACKAGE_FORMAT "1")
set(common_msgs_BUILD_DEPENDS )
set(common_msgs_BUILD_EXPORT_DEPENDS "actionlib_msgs" "diagnostic_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "shape_msgs" "stereo_msgs" "trajectory_msgs" "visualization_msgs")
set(common_msgs_BUILDTOOL_DEPENDS "catkin")
set(common_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(common_msgs_EXEC_DEPENDS "actionlib_msgs" "diagnostic_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "shape_msgs" "stereo_msgs" "trajectory_msgs" "visualization_msgs")
set(common_msgs_RUN_DEPENDS "actionlib_msgs" "diagnostic_msgs" "geometry_msgs" "nav_msgs" "sensor_msgs" "shape_msgs" "stereo_msgs" "trajectory_msgs" "visualization_msgs")
set(common_msgs_TEST_DEPENDS )
set(common_msgs_DOC_DEPENDS )
set(common_msgs_DEPRECATED "")