# CMake generated Testfile for 
# Source directory: /opt/ros_catkin_ws/src/geometry/tf
# Build directory: /opt/ros_catkin_ws/build_isolated/tf
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_tf_gtest_tf_unittest "/opt/ros_catkin_ws/build_isolated/tf/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/gtest-tf_unittest.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/tf/lib/tf/tf_unittest --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/gtest-tf_unittest.xml")
add_test(_ctest_tf_gtest_tf_quaternion_unittest "/opt/ros_catkin_ws/build_isolated/tf/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/gtest-tf_quaternion_unittest.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/tf/lib/tf/tf_quaternion_unittest --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/gtest-tf_quaternion_unittest.xml")
add_test(_ctest_tf_gtest_test_transform_datatypes "/opt/ros_catkin_ws/build_isolated/tf/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/gtest-test_transform_datatypes.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/tf/lib/tf/test_transform_datatypes --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/gtest-test_transform_datatypes.xml")
add_test(_ctest_tf_rostest_test_transform_listener_unittest.launch "/opt/ros_catkin_ws/build_isolated/tf/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/rostest-test_transform_listener_unittest.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/geometry/tf --package=tf --results-filename test_transform_listener_unittest.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/tf/test_results\" /opt/ros_catkin_ws/src/geometry/tf/test/transform_listener_unittest.launch ")
add_test(_ctest_tf_gtest_test_velocity "/opt/ros_catkin_ws/build_isolated/tf/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/gtest-test_velocity.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/tf/lib/tf/test_velocity --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/gtest-test_velocity.xml")
add_test(_ctest_tf_gtest_cache_unittest "/opt/ros_catkin_ws/build_isolated/tf/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/gtest-cache_unittest.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/tf/lib/tf/cache_unittest --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/gtest-cache_unittest.xml")
add_test(_ctest_tf_rostest_test_test_message_filter.xml "/opt/ros_catkin_ws/build_isolated/tf/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/rostest-test_test_message_filter.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/geometry/tf --package=tf --results-filename test_test_message_filter.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/tf/test_results\" /opt/ros_catkin_ws/src/geometry/tf/test/test_message_filter.xml ")
add_test(_ctest_tf_rostest_test_test_broadcaster.launch "/opt/ros_catkin_ws/build_isolated/tf/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/rostest-test_test_broadcaster.xml" "--return-code" "/opt/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/opt/ros_catkin_ws/src/geometry/tf --package=tf --results-filename test_test_broadcaster.xml --results-base-dir \"/opt/ros_catkin_ws/build_isolated/tf/test_results\" /opt/ros_catkin_ws/src/geometry/tf/test/test_broadcaster.launch ")
add_test(_ctest_tf_nosetests_test.testPython.py "/opt/ros_catkin_ws/build_isolated/tf/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/nosetests-test.testPython.py.xml" "--return-code" "/usr/bin/cmake -E make_directory /opt/ros_catkin_ws/build_isolated/tf/test_results/tf" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /opt/ros_catkin_ws/src/geometry/tf/test/testPython.py --with-xunit --xunit-file=/opt/ros_catkin_ws/build_isolated/tf/test_results/tf/nosetests-test.testPython.py.xml")
subdirs(gtest)
