set(_CATKIN_CURRENT_PACKAGE "bond_core")
set(bond_core_VERSION "1.7.16")
set(bond_core_MAINTAINER "Esteve Fernandez <esteve@osrfoundation.org>")
set(bond_core_PACKAGE_FORMAT "1")
set(bond_core_BUILD_DEPENDS )
set(bond_core_BUILD_EXPORT_DEPENDS "bond" "bondcpp" "bondpy" "smclib")
set(bond_core_BUILDTOOL_DEPENDS "catkin")
set(bond_core_BUILDTOOL_EXPORT_DEPENDS )
set(bond_core_EXEC_DEPENDS "bond" "bondcpp" "bondpy" "smclib")
set(bond_core_RUN_DEPENDS "bond" "bondcpp" "bondpy" "smclib")
set(bond_core_TEST_DEPENDS )
set(bond_core_DOC_DEPENDS )
set(bond_core_DEPRECATED "")