set(_CATKIN_CURRENT_PACKAGE "rosmake")
set(rosmake_VERSION "1.12.7")
set(rosmake_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosmake_PACKAGE_FORMAT "1")
set(rosmake_BUILD_DEPENDS )
set(rosmake_BUILD_EXPORT_DEPENDS "catkin" "python-rospkg")
set(rosmake_BUILDTOOL_DEPENDS "catkin")
set(rosmake_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(rosmake_BUILDTOOL_EXPORT_DEPENDS )
set(rosmake_EXEC_DEPENDS "catkin" "python-rospkg")
set(rosmake_RUN_DEPENDS "catkin" "python-rospkg")
set(rosmake_TEST_DEPENDS )
set(rosmake_DOC_DEPENDS )
set(rosmake_DEPRECATED "")