set(rosmake_SETUP_PY_VERSION "1.12.7")
set(rosmake_SETUP_PY_SCRIPTS "scripts/rosmake")
set(rosmake_SETUP_PY_PACKAGES "rosmake")
set(rosmake_SETUP_PY_PACKAGE_DIRS "src/rosmake")
set(rosmake_SETUP_PY_MODULES "")
set(rosmake_SETUP_PY_MODULE_DIRS "")