set(_CATKIN_CURRENT_PACKAGE "rqt_graph")
set(rqt_graph_VERSION "0.3.13")
set(rqt_graph_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_graph_PACKAGE_FORMAT "1")
set(rqt_graph_BUILD_DEPENDS )
set(rqt_graph_BUILD_EXPORT_DEPENDS "python-rospkg" "qt_dotgraph" "rosgraph" "rosgraph_msgs" "roslib" "rosnode" "rospy" "rosservice" "rostopic" "rqt_gui" "rqt_gui_py")
set(rqt_graph_BUILDTOOL_DEPENDS "catkin")
set(rqt_graph_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_graph_EXEC_DEPENDS "python-rospkg" "qt_dotgraph" "rosgraph" "rosgraph_msgs" "roslib" "rosnode" "rospy" "rosservice" "rostopic" "rqt_gui" "rqt_gui_py")
set(rqt_graph_RUN_DEPENDS "python-rospkg" "qt_dotgraph" "rosgraph" "rosgraph_msgs" "roslib" "rosnode" "rospy" "rosservice" "rostopic" "rqt_gui" "rqt_gui_py")
set(rqt_graph_TEST_DEPENDS )
set(rqt_graph_DOC_DEPENDS )
set(rqt_graph_DEPRECATED "")