set(_CATKIN_CURRENT_PACKAGE "roslisp")
set(roslisp_VERSION "1.9.20")
set(roslisp_MAINTAINER "Georg Bartels <georg.bartels@cs.uni-bremen.de>, Lorenz Moesenlechner <moesenle@cs.tum.edu>")
set(roslisp_PACKAGE_FORMAT "1")
set(roslisp_BUILD_DEPENDS )
set(roslisp_BUILD_EXPORT_DEPENDS "roslang" "sbcl" "rospack" "rosgraph_msgs" "std_srvs")
set(roslisp_BUILDTOOL_DEPENDS "catkin")
set(roslisp_BUILDTOOL_EXPORT_DEPENDS )
set(roslisp_EXEC_DEPENDS "roslang" "sbcl" "rospack" "rosgraph_msgs" "std_srvs")
set(roslisp_RUN_DEPENDS "roslang" "sbcl" "rospack" "rosgraph_msgs" "std_srvs")
set(roslisp_TEST_DEPENDS )
set(roslisp_DOC_DEPENDS )
set(roslisp_DEPRECATED "")