set(_CATKIN_CURRENT_PACKAGE "rqt_robot_monitor")
set(rqt_robot_monitor_VERSION "0.4.3")
set(rqt_robot_monitor_MAINTAINER "Austin Hendrix <namniart@gmail.com>")
set(rqt_robot_monitor_PACKAGE_FORMAT "1")
set(rqt_robot_monitor_BUILD_DEPENDS )
set(rqt_robot_monitor_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "python_qt_binding" "python-rospkg" "qt_gui" "qt_gui_py_common" "rospy" "rqt_py_common" "rqt_gui" "rqt_gui_py" "rqt_bag")
set(rqt_robot_monitor_BUILDTOOL_DEPENDS "catkin")
set(rqt_robot_monitor_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_robot_monitor_EXEC_DEPENDS "diagnostic_msgs" "python_qt_binding" "python-rospkg" "qt_gui" "qt_gui_py_common" "rospy" "rqt_py_common" "rqt_gui" "rqt_gui_py" "rqt_bag")
set(rqt_robot_monitor_RUN_DEPENDS "diagnostic_msgs" "python_qt_binding" "python-rospkg" "qt_gui" "qt_gui_py_common" "rospy" "rqt_py_common" "rqt_gui" "rqt_gui_py" "rqt_bag")
set(rqt_robot_monitor_TEST_DEPENDS )
set(rqt_robot_monitor_DOC_DEPENDS )
set(rqt_robot_monitor_DEPRECATED "")