set(_CATKIN_CURRENT_PACKAGE "rosbag")
set(rosbag_VERSION "1.11.19")
set(rosbag_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosbag_PACKAGE_FORMAT "1")
set(rosbag_BUILD_DEPENDS "boost" "cpp_common" "python-imaging" "rosbag_storage" "rosconsole" "roscpp" "roscpp_serialization" "topic_tools" "xmlrpcpp")
set(rosbag_BUILD_EXPORT_DEPENDS "boost" "genmsg" "genpy" "python-rospkg" "rosbag_storage" "rosconsole" "roscpp" "roslib" "rospy" "topic_tools" "xmlrpcpp")
set(rosbag_BUILDTOOL_DEPENDS "catkin")
set(rosbag_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(rosbag_BUILDTOOL_EXPORT_DEPENDS )
set(rosbag_EXEC_DEPENDS "boost" "genmsg" "genpy" "python-rospkg" "rosbag_storage" "rosconsole" "roscpp" "roslib" "rospy" "topic_tools" "xmlrpcpp")
set(rosbag_RUN_DEPENDS "boost" "genmsg" "genpy" "python-rospkg" "rosbag_storage" "rosconsole" "roscpp" "roslib" "rospy" "topic_tools" "xmlrpcpp")
set(rosbag_TEST_DEPENDS )
set(rosbag_DOC_DEPENDS )
set(rosbag_DEPRECATED "")