set(_CATKIN_CURRENT_PACKAGE "filters")
set(filters_VERSION "1.7.4")
set(filters_MAINTAINER "Tully Foote <tfoote@willowgarage.com>")
set(filters_PACKAGE_FORMAT "1")
set(filters_BUILD_DEPENDS "roslib" "rosconsole" "roscpp" "pluginlib" "rostest")
set(filters_BUILD_EXPORT_DEPENDS "roslib" "rosconsole" "roscpp" "pluginlib")
set(filters_BUILDTOOL_DEPENDS "catkin")
set(filters_BUILDTOOL_EXPORT_DEPENDS )
set(filters_EXEC_DEPENDS "roslib" "rosconsole" "roscpp" "pluginlib")
set(filters_RUN_DEPENDS "roslib" "rosconsole" "roscpp" "pluginlib")
set(filters_TEST_DEPENDS )
set(filters_DOC_DEPENDS )
set(filters_DEPRECATED "")