set(_CATKIN_CURRENT_PACKAGE "self_test")
set(self_test_VERSION "1.8.9")
set(self_test_MAINTAINER "Brice Rebsamen <brice.rebsamen@gmail.com>, Austin Hendrix <namniart@gmail.com>")
set(self_test_PACKAGE_FORMAT "1")
set(self_test_BUILD_DEPENDS "diagnostic_msgs" "diagnostic_updater" "roscpp" "rostest")
set(self_test_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "diagnostic_updater" "roscpp")
set(self_test_BUILDTOOL_DEPENDS "catkin")
set(self_test_BUILDTOOL_EXPORT_DEPENDS )
set(self_test_EXEC_DEPENDS "diagnostic_msgs" "diagnostic_updater" "roscpp")
set(self_test_RUN_DEPENDS "diagnostic_msgs" "diagnostic_updater" "roscpp")
set(self_test_TEST_DEPENDS )
set(self_test_DOC_DEPENDS )
set(self_test_DEPRECATED "")