set(_CATKIN_CURRENT_PACKAGE "geometry")
set(geometry_VERSION "1.11.8")
set(geometry_MAINTAINER "Tully Foote <tfoote@osrfoundation.org>")
set(geometry_PACKAGE_FORMAT "1")
set(geometry_BUILD_DEPENDS )
set(geometry_BUILD_EXPORT_DEPENDS "angles" "eigen_conversions" "kdl_conversions" "tf" "tf_conversions")
set(geometry_BUILDTOOL_DEPENDS "catkin")
set(geometry_BUILDTOOL_EXPORT_DEPENDS )
set(geometry_EXEC_DEPENDS "angles" "eigen_conversions" "kdl_conversions" "tf" "tf_conversions")
set(geometry_RUN_DEPENDS "angles" "eigen_conversions" "kdl_conversions" "tf" "tf_conversions")
set(geometry_TEST_DEPENDS )
set(geometry_DOC_DEPENDS )
set(geometry_DEPRECATED "")