set(_CATKIN_CURRENT_PACKAGE "pluginlib_tutorials")
set(pluginlib_tutorials_VERSION "0.1.8")
set(pluginlib_tutorials_MAINTAINER "Daniel Stonier <d.stonier@gmail.com>")
set(pluginlib_tutorials_PACKAGE_FORMAT "1")
set(pluginlib_tutorials_BUILD_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials_BUILD_EXPORT_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials_BUILDTOOL_DEPENDS "catkin")
set(pluginlib_tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(pluginlib_tutorials_EXEC_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials_RUN_DEPENDS "pluginlib" "roscpp")
set(pluginlib_tutorials_TEST_DEPENDS )
set(pluginlib_tutorials_DOC_DEPENDS )
set(pluginlib_tutorials_DEPRECATED "")