set(_CATKIN_CURRENT_PACKAGE "rosbash")
set(rosbash_VERSION "1.12.7")
set(rosbash_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosbash_PACKAGE_FORMAT "1")
set(rosbash_BUILD_DEPENDS )
set(rosbash_BUILD_EXPORT_DEPENDS "catkin")
set(rosbash_BUILDTOOL_DEPENDS "catkin")
set(rosbash_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.72")
set(rosbash_BUILDTOOL_EXPORT_DEPENDS )
set(rosbash_EXEC_DEPENDS "catkin")
set(rosbash_RUN_DEPENDS "catkin")
set(rosbash_TEST_DEPENDS )
set(rosbash_DOC_DEPENDS )
set(rosbash_DEPRECATED "")