set(_CATKIN_CURRENT_PACKAGE "pluginlib")
set(pluginlib_VERSION "1.10.2")
set(pluginlib_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(pluginlib_PACKAGE_FORMAT "1")
set(pluginlib_BUILD_DEPENDS "boost" "cmake_modules" "class_loader" "rosconsole" "roslib" "tinyxml")
set(pluginlib_BUILD_DEPENDS_roslib_VERSION_GTE "1.11.1")
set(pluginlib_BUILD_EXPORT_DEPENDS "boost" "class_loader" "rosconsole" "roslib" "tinyxml")
set(pluginlib_BUILD_EXPORT_DEPENDS_roslib_VERSION_GTE "1.11.1")
set(pluginlib_BUILDTOOL_DEPENDS "catkin")
set(pluginlib_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(pluginlib_BUILDTOOL_EXPORT_DEPENDS )
set(pluginlib_EXEC_DEPENDS "boost" "class_loader" "rosconsole" "roslib" "tinyxml")
set(pluginlib_EXEC_DEPENDS_roslib_VERSION_GTE "1.11.1")
set(pluginlib_RUN_DEPENDS "boost" "class_loader" "rosconsole" "roslib" "tinyxml")
set(pluginlib_RUN_DEPENDS_roslib_VERSION_GTE "1.11.1")
set(pluginlib_TEST_DEPENDS )
set(pluginlib_DOC_DEPENDS )
set(pluginlib_DEPRECATED "")