set(pluginlib_SETUP_PY_VERSION "1.10.2")
set(pluginlib_SETUP_PY_SCRIPTS "")
set(pluginlib_SETUP_PY_PACKAGES "")
set(pluginlib_SETUP_PY_PACKAGE_DIRS "")
set(pluginlib_SETUP_PY_MODULES "")
set(pluginlib_SETUP_PY_MODULE_DIRS "")