set(smclib_SETUP_PY_VERSION "1.7.16")
set(smclib_SETUP_PY_SCRIPTS "")
set(smclib_SETUP_PY_PACKAGES "smclib")
set(smclib_SETUP_PY_PACKAGE_DIRS "python/smclib")
set(smclib_SETUP_PY_MODULES "")
set(smclib_SETUP_PY_MODULE_DIRS "")