# CMake generated Testfile for 
# Source directory: /opt/ros_catkin_ws/src/rviz/src/test
# Build directory: /opt/ros_catkin_ws/build_isolated/rviz/src/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rviz_gtest_property_test "/opt/ros_catkin_ws/build_isolated/rviz/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rviz/test_results/rviz/gtest-property_test.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/rviz/lib/rviz/property_test --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/rviz/test_results/rviz/gtest-property_test.xml")
add_test(_ctest_rviz_gtest_uniform_string_stream_test "/opt/ros_catkin_ws/build_isolated/rviz/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rviz/test_results/rviz/gtest-uniform_string_stream_test.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/rviz/lib/rviz/uniform_string_stream_test --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/rviz/test_results/rviz/gtest-uniform_string_stream_test.xml")
add_test(_ctest_rviz_gtest_property_with_ros_spinner_test "/opt/ros_catkin_ws/build_isolated/rviz/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rviz/test_results/rviz/gtest-property_with_ros_spinner_test.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/rviz/lib/rviz/property_with_ros_spinner_test --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/rviz/test_results/rviz/gtest-property_with_ros_spinner_test.xml")
add_test(_ctest_rviz_gtest_config_test "/opt/ros_catkin_ws/build_isolated/rviz/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rviz/test_results/rviz/gtest-config_test.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/rviz/lib/rviz/config_test --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/rviz/test_results/rviz/gtest-config_test.xml")
add_test(_ctest_rviz_gtest_stl_loader_test "/opt/ros_catkin_ws/build_isolated/rviz/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/opt/ros_catkin_ws/build_isolated/rviz/test_results/rviz/gtest-stl_loader_test.xml" "--return-code" "/opt/ros_catkin_ws/devel_isolated/rviz/lib/rviz/stl_loader_test --gtest_output=xml:/opt/ros_catkin_ws/build_isolated/rviz/test_results/rviz/gtest-stl_loader_test.xml")
