set(_CATKIN_CURRENT_PACKAGE "dynamic_reconfigure")
set(dynamic_reconfigure_VERSION "1.5.43")
set(dynamic_reconfigure_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(dynamic_reconfigure_PACKAGE_FORMAT "1")
set(dynamic_reconfigure_BUILD_DEPENDS "boost" "message_generation" "roscpp" "roscpp_serialization" "rostest" "std_msgs")
set(dynamic_reconfigure_BUILD_EXPORT_DEPENDS "boost" "message_runtime" "roscpp" "roslib" "rospy" "rosservice" "std_msgs")
set(dynamic_reconfigure_BUILDTOOL_DEPENDS "catkin")
set(dynamic_reconfigure_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.87")
set(dynamic_reconfigure_BUILDTOOL_EXPORT_DEPENDS )
set(dynamic_reconfigure_EXEC_DEPENDS "boost" "message_runtime" "roscpp" "roslib" "rospy" "rosservice" "std_msgs")
set(dynamic_reconfigure_RUN_DEPENDS "boost" "message_runtime" "roscpp" "roslib" "rospy" "rosservice" "std_msgs")
set(dynamic_reconfigure_TEST_DEPENDS )
set(dynamic_reconfigure_DOC_DEPENDS )
set(dynamic_reconfigure_DEPRECATED "")