set(_CATKIN_CURRENT_PACKAGE "robot")
set(robot_VERSION "1.2.0")
set(robot_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(robot_PACKAGE_FORMAT "1")
set(robot_BUILD_DEPENDS )
set(robot_BUILD_EXPORT_DEPENDS "ros_base" "control_msgs" "diagnostics" "executive_smach" "filters" "geometry" "robot_model" "robot_state_publisher" "xacro")
set(robot_BUILDTOOL_DEPENDS "catkin")
set(robot_BUILDTOOL_EXPORT_DEPENDS )
set(robot_EXEC_DEPENDS "ros_base" "control_msgs" "diagnostics" "executive_smach" "filters" "geometry" "robot_model" "robot_state_publisher" "xacro")
set(robot_RUN_DEPENDS "ros_base" "control_msgs" "diagnostics" "executive_smach" "filters" "geometry" "robot_model" "robot_state_publisher" "xacro")
set(robot_TEST_DEPENDS )
set(robot_DOC_DEPENDS )
set(robot_DEPRECATED "")