set(_CATKIN_CURRENT_PACKAGE "ros_core")
set(ros_core_VERSION "1.2.0")
set(ros_core_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(ros_core_PACKAGE_FORMAT "1")
set(ros_core_BUILD_DEPENDS )
set(ros_core_BUILD_EXPORT_DEPENDS "catkin" "cmake_modules" "common_msgs" "gencpp" "geneus" "genlisp" "genmsg" "genpy" "message_generation" "message_runtime" "ros" "ros_comm" "rosbag_migration_rule" "rosconsole_bridge" "roscpp_core" "rosgraph_msgs" "roslisp" "rospack" "std_msgs" "std_srvs")
set(ros_core_BUILDTOOL_DEPENDS "catkin")
set(ros_core_BUILDTOOL_EXPORT_DEPENDS )
set(ros_core_EXEC_DEPENDS "catkin" "cmake_modules" "common_msgs" "gencpp" "geneus" "genlisp" "genmsg" "genpy" "message_generation" "message_runtime" "ros" "ros_comm" "rosbag_migration_rule" "rosconsole_bridge" "roscpp_core" "rosgraph_msgs" "roslisp" "rospack" "std_msgs" "std_srvs")
set(ros_core_RUN_DEPENDS "catkin" "cmake_modules" "common_msgs" "gencpp" "geneus" "genlisp" "genmsg" "genpy" "message_generation" "message_runtime" "ros" "ros_comm" "rosbag_migration_rule" "rosconsole_bridge" "roscpp_core" "rosgraph_msgs" "roslisp" "rospack" "std_msgs" "std_srvs")
set(ros_core_TEST_DEPENDS )
set(ros_core_DOC_DEPENDS )
set(ros_core_DEPRECATED "")