set(_CATKIN_CURRENT_PACKAGE "rqt_pose_view")
set(rqt_pose_view_VERSION "0.4.3")
set(rqt_pose_view_MAINTAINER "Dorian Scholz <scholz@sim.tu-darmstadt.de>, Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_pose_view_PACKAGE_FORMAT "1")
set(rqt_pose_view_BUILD_DEPENDS )
set(rqt_pose_view_BUILD_EXPORT_DEPENDS "geometry_msgs" "python-opengl" "python_qt_binding" "python-qt-bindings-gl" "python-rospkg" "rospy" "rostopic" "rqt_gui" "rqt_gui_py" "tf")
set(rqt_pose_view_BUILDTOOL_DEPENDS "catkin")
set(rqt_pose_view_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_pose_view_EXEC_DEPENDS "geometry_msgs" "python-opengl" "python_qt_binding" "python-qt-bindings-gl" "python-rospkg" "rospy" "rostopic" "rqt_gui" "rqt_gui_py" "tf")
set(rqt_pose_view_RUN_DEPENDS "geometry_msgs" "python-opengl" "python_qt_binding" "python-qt-bindings-gl" "python-rospkg" "rospy" "rostopic" "rqt_gui" "rqt_gui_py" "tf")
set(rqt_pose_view_TEST_DEPENDS )
set(rqt_pose_view_DOC_DEPENDS )
set(rqt_pose_view_DEPRECATED "")