set(diagnostic_updater_SETUP_PY_VERSION "1.8.9")
set(diagnostic_updater_SETUP_PY_SCRIPTS "")
set(diagnostic_updater_SETUP_PY_PACKAGES "diagnostic_updater")
set(diagnostic_updater_SETUP_PY_PACKAGE_DIRS "src/diagnostic_updater")
set(diagnostic_updater_SETUP_PY_MODULES "")
set(diagnostic_updater_SETUP_PY_MODULE_DIRS "")