set(_CATKIN_CURRENT_PACKAGE "python_qt_binding")
set(python_qt_binding_VERSION "0.2.19")
set(python_qt_binding_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(python_qt_binding_PACKAGE_FORMAT "1")
set(python_qt_binding_BUILD_DEPENDS "rosbuild" "qt4-qmake" "python-qt-bindings")
set(python_qt_binding_BUILD_EXPORT_DEPENDS "python-qt-bindings")
set(python_qt_binding_BUILDTOOL_DEPENDS "catkin")
set(python_qt_binding_BUILDTOOL_EXPORT_DEPENDS )
set(python_qt_binding_EXEC_DEPENDS "python-qt-bindings")
set(python_qt_binding_RUN_DEPENDS "python-qt-bindings")
set(python_qt_binding_TEST_DEPENDS )
set(python_qt_binding_DOC_DEPENDS )
set(python_qt_binding_DEPRECATED "")