set(_CATKIN_CURRENT_PACKAGE "nodelet")
set(nodelet_VERSION "1.9.4")
set(nodelet_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(nodelet_PACKAGE_FORMAT "1")
set(nodelet_BUILD_DEPENDS "bondcpp" "boost" "cmake_modules" "message_generation" "pluginlib" "rosconsole" "roscpp" "rospy" "std_msgs" "tinyxml" "uuid")
set(nodelet_BUILD_DEPENDS_cmake_modules_VERSION_GTE "0.3.2")
set(nodelet_BUILD_DEPENDS_pluginlib_VERSION_GTE "1.10.0")
set(nodelet_BUILD_EXPORT_DEPENDS "bondcpp" "boost" "message_runtime" "pluginlib" "rosconsole" "roscpp" "std_msgs" "tinyxml" "uuid")
set(nodelet_BUILD_EXPORT_DEPENDS_pluginlib_VERSION_GTE "1.10.0")
set(nodelet_BUILDTOOL_DEPENDS "catkin")
set(nodelet_BUILDTOOL_EXPORT_DEPENDS )
set(nodelet_EXEC_DEPENDS "bondcpp" "boost" "message_runtime" "pluginlib" "rosconsole" "roscpp" "std_msgs" "tinyxml" "uuid")
set(nodelet_EXEC_DEPENDS_pluginlib_VERSION_GTE "1.10.0")
set(nodelet_RUN_DEPENDS "bondcpp" "boost" "message_runtime" "pluginlib" "rosconsole" "roscpp" "std_msgs" "tinyxml" "uuid")
set(nodelet_RUN_DEPENDS_pluginlib_VERSION_GTE "1.10.0")
set(nodelet_TEST_DEPENDS )
set(nodelet_DOC_DEPENDS )
set(nodelet_DEPRECATED "")