set(_CATKIN_CURRENT_PACKAGE "xacro")
set(xacro_VERSION "1.10.6")
set(xacro_MAINTAINER "Morgan Quigley <morgan@osrfoundation.org>")
set(xacro_PACKAGE_FORMAT "1")
set(xacro_BUILD_DEPENDS "roslint")
set(xacro_BUILD_EXPORT_DEPENDS "roslaunch")
set(xacro_BUILDTOOL_DEPENDS "catkin")
set(xacro_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(xacro_BUILDTOOL_EXPORT_DEPENDS )
set(xacro_EXEC_DEPENDS "roslaunch")
set(xacro_RUN_DEPENDS "roslaunch")
set(xacro_TEST_DEPENDS "rostest")
set(xacro_DOC_DEPENDS )
set(xacro_DEPRECATED "")