set(_CATKIN_CURRENT_PACKAGE "rqt_plot")
set(rqt_plot_VERSION "0.3.13")
set(rqt_plot_MAINTAINER "Dorian Scholz <scholz@sim.tu-darmstadt.de>, Austin Hendrix <namniart@gmail.com>")
set(rqt_plot_PACKAGE_FORMAT "1")
set(rqt_plot_BUILD_DEPENDS )
set(rqt_plot_BUILD_EXPORT_DEPENDS "python-matplotlib" "python-qt-bindings-qwt5" "python-rospkg" "qt_gui_py_common" "rosgraph" "rostopic" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_plot_BUILD_EXPORT_DEPENDS_qt_gui_py_common_VERSION_GTE "0.2.25")
set(rqt_plot_BUILDTOOL_DEPENDS "catkin")
set(rqt_plot_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_plot_EXEC_DEPENDS "python-matplotlib" "python-qt-bindings-qwt5" "python-rospkg" "qt_gui_py_common" "rosgraph" "rostopic" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_plot_EXEC_DEPENDS_qt_gui_py_common_VERSION_GTE "0.2.25")
set(rqt_plot_RUN_DEPENDS "python-matplotlib" "python-qt-bindings-qwt5" "python-rospkg" "qt_gui_py_common" "rosgraph" "rostopic" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_plot_RUN_DEPENDS_qt_gui_py_common_VERSION_GTE "0.2.25")
set(rqt_plot_TEST_DEPENDS )
set(rqt_plot_DOC_DEPENDS )
set(rqt_plot_DEPRECATED "")