set(rqt_plot_SETUP_PY_VERSION "0.3.13")
set(rqt_plot_SETUP_PY_SCRIPTS "scripts/rqt_plot")
set(rqt_plot_SETUP_PY_PACKAGES "rqt_plot")
set(rqt_plot_SETUP_PY_PACKAGE_DIRS "src/rqt_plot")
set(rqt_plot_SETUP_PY_MODULES "")
set(rqt_plot_SETUP_PY_MODULE_DIRS "")