set(_CATKIN_CURRENT_PACKAGE "rqt_launch")
set(rqt_launch_VERSION "0.3.13")
set(rqt_launch_MAINTAINER "Isaac Saito <130s@lateeye.net>")
set(rqt_launch_PACKAGE_FORMAT "1")
set(rqt_launch_BUILD_DEPENDS "rqt_py_common")
set(rqt_launch_BUILD_EXPORT_DEPENDS "roslaunch" "rospy" "rqt_console" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_launch_BUILDTOOL_DEPENDS "catkin")
set(rqt_launch_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_launch_EXEC_DEPENDS "roslaunch" "rospy" "rqt_console" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_launch_RUN_DEPENDS "roslaunch" "rospy" "rqt_console" "rqt_gui" "rqt_gui_py" "rqt_py_common")
set(rqt_launch_TEST_DEPENDS )
set(rqt_launch_DOC_DEPENDS )
set(rqt_launch_DEPRECATED "")