set(_CATKIN_CURRENT_PACKAGE "rosclean")
set(rosclean_VERSION "1.12.7")
set(rosclean_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(rosclean_PACKAGE_FORMAT "1")
set(rosclean_BUILD_DEPENDS )
set(rosclean_BUILD_EXPORT_DEPENDS "python-rospkg")
set(rosclean_BUILDTOOL_DEPENDS "catkin")
set(rosclean_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(rosclean_BUILDTOOL_EXPORT_DEPENDS )
set(rosclean_EXEC_DEPENDS "python-rospkg")
set(rosclean_RUN_DEPENDS "python-rospkg")
set(rosclean_TEST_DEPENDS )
set(rosclean_DOC_DEPENDS )
set(rosclean_DEPRECATED "")