set(_CATKIN_CURRENT_PACKAGE "rqt_nav_view")
set(rqt_nav_view_VERSION "0.4.3")
set(rqt_nav_view_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_nav_view_PACKAGE_FORMAT "1")
set(rqt_nav_view_BUILD_DEPENDS )
set(rqt_nav_view_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "python_qt_binding" "qt_gui" "rospy" "rqt_gui" "rqt_gui_py" "rqt_py_common" "tf")
set(rqt_nav_view_BUILDTOOL_DEPENDS "catkin")
set(rqt_nav_view_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_nav_view_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "python_qt_binding" "qt_gui" "rospy" "rqt_gui" "rqt_gui_py" "rqt_py_common" "tf")
set(rqt_nav_view_RUN_DEPENDS "geometry_msgs" "nav_msgs" "python_qt_binding" "qt_gui" "rospy" "rqt_gui" "rqt_gui_py" "rqt_py_common" "tf")
set(rqt_nav_view_TEST_DEPENDS )
set(rqt_nav_view_DOC_DEPENDS )
set(rqt_nav_view_DEPRECATED "")