set(_CATKIN_CURRENT_PACKAGE "roscpp_serialization")
set(roscpp_serialization_VERSION "0.5.7")
set(roscpp_serialization_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(roscpp_serialization_PACKAGE_FORMAT "1")
set(roscpp_serialization_BUILD_DEPENDS "cpp_common" "roscpp_traits" "rostime")
set(roscpp_serialization_BUILD_EXPORT_DEPENDS "cpp_common" "roscpp_traits" "rostime")
set(roscpp_serialization_BUILDTOOL_DEPENDS "catkin")
set(roscpp_serialization_BUILDTOOL_EXPORT_DEPENDS )
set(roscpp_serialization_EXEC_DEPENDS "cpp_common" "roscpp_traits" "rostime")
set(roscpp_serialization_RUN_DEPENDS "cpp_common" "roscpp_traits" "rostime")
set(roscpp_serialization_TEST_DEPENDS )
set(roscpp_serialization_DOC_DEPENDS )
set(roscpp_serialization_DEPRECATED "")