set(_CATKIN_CURRENT_PACKAGE "bondpy")
set(bondpy_VERSION "1.7.16")
set(bondpy_MAINTAINER "Esteve Fernandez <esteve@osrfoundation.org>")
set(bondpy_PACKAGE_FORMAT "1")
set(bondpy_BUILD_DEPENDS "bond" "rospy" "smclib")
set(bondpy_BUILD_EXPORT_DEPENDS "rospy" "smclib" "uuid")
set(bondpy_BUILDTOOL_DEPENDS "catkin")
set(bondpy_BUILDTOOL_EXPORT_DEPENDS )
set(bondpy_EXEC_DEPENDS "rospy" "smclib" "uuid")
set(bondpy_RUN_DEPENDS "rospy" "smclib" "uuid")
set(bondpy_TEST_DEPENDS )
set(bondpy_DOC_DEPENDS )
set(bondpy_DEPRECATED "")