set(rostopic_SETUP_PY_VERSION "1.11.19")
set(rostopic_SETUP_PY_SCRIPTS "scripts/rostopic")
set(rostopic_SETUP_PY_PACKAGES "rostopic")
set(rostopic_SETUP_PY_PACKAGE_DIRS "src/rostopic")
set(rostopic_SETUP_PY_MODULES "")
set(rostopic_SETUP_PY_MODULE_DIRS "")