set(_CATKIN_CURRENT_PACKAGE "message_generation")
set(message_generation_VERSION "0.3.0")
set(message_generation_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(message_generation_PACKAGE_FORMAT "1")
set(message_generation_BUILD_DEPENDS )
set(message_generation_BUILD_EXPORT_DEPENDS "gencpp" "geneus" "genlisp" "genmsg" "genpy")
set(message_generation_BUILDTOOL_DEPENDS "catkin")
set(message_generation_BUILDTOOL_EXPORT_DEPENDS )
set(message_generation_EXEC_DEPENDS "gencpp" "geneus" "genlisp" "genmsg" "genpy")
set(message_generation_RUN_DEPENDS "gencpp" "geneus" "genlisp" "genmsg" "genpy")
set(message_generation_TEST_DEPENDS )
set(message_generation_DOC_DEPENDS )
set(message_generation_DEPRECATED "")