set(_CATKIN_CURRENT_PACKAGE "message_runtime")
set(message_runtime_VERSION "0.4.12")
set(message_runtime_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(message_runtime_PACKAGE_FORMAT "1")
set(message_runtime_BUILD_DEPENDS )
set(message_runtime_BUILD_EXPORT_DEPENDS "cpp_common" "roscpp_serialization" "roscpp_traits" "rostime" "genpy")
set(message_runtime_BUILDTOOL_DEPENDS "catkin")
set(message_runtime_BUILDTOOL_EXPORT_DEPENDS )
set(message_runtime_EXEC_DEPENDS "cpp_common" "roscpp_serialization" "roscpp_traits" "rostime" "genpy")
set(message_runtime_RUN_DEPENDS "cpp_common" "roscpp_serialization" "roscpp_traits" "rostime" "genpy")
set(message_runtime_TEST_DEPENDS )
set(message_runtime_DOC_DEPENDS )
set(message_runtime_DEPRECATED "")