set(_CATKIN_CURRENT_PACKAGE "rviz_python_tutorial")
set(rviz_python_tutorial_VERSION "0.9.2")
set(rviz_python_tutorial_MAINTAINER "William Woodall <william@osrfoundation.org>")
set(rviz_python_tutorial_PACKAGE_FORMAT "1")
set(rviz_python_tutorial_BUILD_DEPENDS "rviz")
set(rviz_python_tutorial_BUILD_EXPORT_DEPENDS "rviz")
set(rviz_python_tutorial_BUILDTOOL_DEPENDS "catkin")
set(rviz_python_tutorial_BUILDTOOL_EXPORT_DEPENDS )
set(rviz_python_tutorial_EXEC_DEPENDS "rviz")
set(rviz_python_tutorial_RUN_DEPENDS "rviz")
set(rviz_python_tutorial_TEST_DEPENDS )
set(rviz_python_tutorial_DOC_DEPENDS )
set(rviz_python_tutorial_DEPRECATED "")