set(_CATKIN_CURRENT_PACKAGE "diagnostic_aggregator")
set(diagnostic_aggregator_VERSION "1.8.9")
set(diagnostic_aggregator_MAINTAINER "Austin Hendrix <namniart@gmail.com>, Brice Rebsamen <brice.rebsamen@gmail.com>")
set(diagnostic_aggregator_PACKAGE_FORMAT "1")
set(diagnostic_aggregator_BUILD_DEPENDS "diagnostic_msgs" "pluginlib" "roscpp" "rospy" "rostest" "xmlrpcpp" "bondcpp" "bondpy")
set(diagnostic_aggregator_BUILD_DEPENDS_diagnostic_msgs_VERSION_GTE "1.12.4")
set(diagnostic_aggregator_BUILD_EXPORT_DEPENDS "diagnostic_msgs" "pluginlib" "roscpp" "rospy" "xmlrpcpp" "bondcpp" "bondpy")
set(diagnostic_aggregator_BUILD_EXPORT_DEPENDS_diagnostic_msgs_VERSION_GTE "1.12.4")
set(diagnostic_aggregator_BUILDTOOL_DEPENDS "catkin")
set(diagnostic_aggregator_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(diagnostic_aggregator_BUILDTOOL_EXPORT_DEPENDS )
set(diagnostic_aggregator_EXEC_DEPENDS "diagnostic_msgs" "pluginlib" "roscpp" "rospy" "xmlrpcpp" "bondcpp" "bondpy")
set(diagnostic_aggregator_EXEC_DEPENDS_diagnostic_msgs_VERSION_GTE "1.12.4")
set(diagnostic_aggregator_RUN_DEPENDS "diagnostic_msgs" "pluginlib" "roscpp" "rospy" "xmlrpcpp" "bondcpp" "bondpy")
set(diagnostic_aggregator_RUN_DEPENDS_diagnostic_msgs_VERSION_GTE "1.12.4")
set(diagnostic_aggregator_TEST_DEPENDS )
set(diagnostic_aggregator_DOC_DEPENDS )
set(diagnostic_aggregator_DEPRECATED "")