set(_CATKIN_CURRENT_PACKAGE "executive_smach")
set(executive_smach_VERSION "2.0.0")
set(executive_smach_MAINTAINER "Jonathan Bohren <jbo@jhu.edu>")
set(executive_smach_PACKAGE_FORMAT "1")
set(executive_smach_BUILD_DEPENDS )
set(executive_smach_BUILD_EXPORT_DEPENDS "smach" "smach_ros" "smach_msgs")
set(executive_smach_BUILDTOOL_DEPENDS "catkin")
set(executive_smach_BUILDTOOL_EXPORT_DEPENDS )
set(executive_smach_EXEC_DEPENDS "smach" "smach_ros" "smach_msgs")
set(executive_smach_RUN_DEPENDS "smach" "smach_ros" "smach_msgs")
set(executive_smach_TEST_DEPENDS )
set(executive_smach_DOC_DEPENDS )
set(executive_smach_DEPRECATED "")