set(_CATKIN_CURRENT_PACKAGE "rqt_dep")
set(rqt_dep_VERSION "0.3.13")
set(rqt_dep_MAINTAINER "Aaron Blasdel <ablasdel@gmail.com>")
set(rqt_dep_PACKAGE_FORMAT "1")
set(rqt_dep_BUILD_DEPENDS )
set(rqt_dep_BUILD_EXPORT_DEPENDS "python-rospkg" "qt_dotgraph" "qt_gui" "qt_gui_py_common" "rqt_graph" "rqt_gui_py")
set(rqt_dep_BUILDTOOL_DEPENDS "catkin")
set(rqt_dep_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_dep_EXEC_DEPENDS "python-rospkg" "qt_dotgraph" "qt_gui" "qt_gui_py_common" "rqt_graph" "rqt_gui_py")
set(rqt_dep_RUN_DEPENDS "python-rospkg" "qt_dotgraph" "qt_gui" "qt_gui_py_common" "rqt_graph" "rqt_gui_py")
set(rqt_dep_TEST_DEPENDS "python-mock")
set(rqt_dep_DOC_DEPENDS )
set(rqt_dep_DEPRECATED "")