set(_CATKIN_CURRENT_PACKAGE "roslib")
set(roslib_VERSION "1.12.7")
set(roslib_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(roslib_PACKAGE_FORMAT "1")
set(roslib_BUILD_DEPENDS "boost" "rospack")
set(roslib_BUILD_EXPORT_DEPENDS "catkin" "python-rospkg" "rospack")
set(roslib_BUILD_EXPORT_DEPENDS_python-rospkg_VERSION_GTE "1.0.37")
set(roslib_BUILDTOOL_DEPENDS "catkin")
set(roslib_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.6.7")
set(roslib_BUILDTOOL_EXPORT_DEPENDS )
set(roslib_EXEC_DEPENDS "catkin" "python-rospkg" "rospack")
set(roslib_EXEC_DEPENDS_python-rospkg_VERSION_GTE "1.0.37")
set(roslib_RUN_DEPENDS "catkin" "python-rospkg" "rospack")
set(roslib_RUN_DEPENDS_python-rospkg_VERSION_GTE "1.0.37")
set(roslib_TEST_DEPENDS )
set(roslib_DOC_DEPENDS )
set(roslib_DEPRECATED "")