set(_CATKIN_CURRENT_PACKAGE "eigen_stl_containers")
set(eigen_stl_containers_VERSION "0.1.4")
set(eigen_stl_containers_MAINTAINER "Ioan Sucan <isucan@willowgarage.com>")
set(eigen_stl_containers_PACKAGE_FORMAT "1")
set(eigen_stl_containers_BUILD_DEPENDS )
set(eigen_stl_containers_BUILD_EXPORT_DEPENDS "eigen")
set(eigen_stl_containers_BUILDTOOL_DEPENDS "catkin")
set(eigen_stl_containers_BUILDTOOL_EXPORT_DEPENDS )
set(eigen_stl_containers_EXEC_DEPENDS "eigen")
set(eigen_stl_containers_RUN_DEPENDS "eigen")
set(eigen_stl_containers_TEST_DEPENDS )
set(eigen_stl_containers_DOC_DEPENDS )
set(eigen_stl_containers_DEPRECATED "")