set(_CATKIN_CURRENT_PACKAGE "ros_base")
set(ros_base_VERSION "1.2.0")
set(ros_base_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(ros_base_PACKAGE_FORMAT "1")
set(ros_base_BUILD_DEPENDS )
set(ros_base_BUILD_EXPORT_DEPENDS "ros_core" "actionlib" "bond_core" "class_loader" "dynamic_reconfigure" "nodelet_core" "pluginlib")
set(ros_base_BUILDTOOL_DEPENDS "catkin")
set(ros_base_BUILDTOOL_EXPORT_DEPENDS )
set(ros_base_EXEC_DEPENDS "ros_core" "actionlib" "bond_core" "class_loader" "dynamic_reconfigure" "nodelet_core" "pluginlib")
set(ros_base_RUN_DEPENDS "ros_core" "actionlib" "bond_core" "class_loader" "dynamic_reconfigure" "nodelet_core" "pluginlib")
set(ros_base_TEST_DEPENDS )
set(ros_base_DOC_DEPENDS )
set(ros_base_DEPRECATED "")