set(_CATKIN_CURRENT_PACKAGE "resource_retriever")
set(resource_retriever_VERSION "1.11.6")
set(resource_retriever_MAINTAINER "Ioan Sucan <isucan@gmail.com>")
set(resource_retriever_PACKAGE_FORMAT "1")
set(resource_retriever_BUILD_DEPENDS "curl" "rosconsole" "roslib")
set(resource_retriever_BUILD_EXPORT_DEPENDS "curl" "rosconsole" "roslib")
set(resource_retriever_BUILDTOOL_DEPENDS "catkin")
set(resource_retriever_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(resource_retriever_BUILDTOOL_EXPORT_DEPENDS )
set(resource_retriever_EXEC_DEPENDS "curl" "rosconsole" "roslib")
set(resource_retriever_RUN_DEPENDS "curl" "rosconsole" "roslib")
set(resource_retriever_TEST_DEPENDS )
set(resource_retriever_DOC_DEPENDS )
set(resource_retriever_DEPRECATED "")