set(resource_retriever_SETUP_PY_VERSION "1.11.6")
set(resource_retriever_SETUP_PY_SCRIPTS "")
set(resource_retriever_SETUP_PY_PACKAGES "resource_retriever")
set(resource_retriever_SETUP_PY_PACKAGE_DIRS "src/resource_retriever")
set(resource_retriever_SETUP_PY_MODULES "")
set(resource_retriever_SETUP_PY_MODULE_DIRS "")