set(_CATKIN_CURRENT_PACKAGE "viz")
set(viz_VERSION "1.2.0")
set(viz_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(viz_PACKAGE_FORMAT "1")
set(viz_BUILD_DEPENDS )
set(viz_BUILD_EXPORT_DEPENDS "ros_base" "rqt_common_plugins" "rqt_robot_plugins" "rviz")
set(viz_BUILDTOOL_DEPENDS "catkin")
set(viz_BUILDTOOL_EXPORT_DEPENDS )
set(viz_EXEC_DEPENDS "ros_base" "rqt_common_plugins" "rqt_robot_plugins" "rviz")
set(viz_RUN_DEPENDS "ros_base" "rqt_common_plugins" "rqt_robot_plugins" "rviz")
set(viz_TEST_DEPENDS )
set(viz_DOC_DEPENDS )
set(viz_DEPRECATED "")