set(_CATKIN_CURRENT_PACKAGE "turtle_actionlib")
set(turtle_actionlib_VERSION "0.1.8")
set(turtle_actionlib_MAINTAINER "Daniel Stonier <d.stonier@gmail.com>")
set(turtle_actionlib_PACKAGE_FORMAT "1")
set(turtle_actionlib_BUILD_DEPENDS "actionlib" "actionlib_msgs" "angles" "message_generation" "rosconsole" "roscpp" "std_msgs" "turtlesim" "geometry_msgs")
set(turtle_actionlib_BUILD_EXPORT_DEPENDS "actionlib" "actionlib_msgs" "angles" "message_runtime" "rosconsole" "roscpp" "std_msgs" "turtlesim" "geometry_msgs")
set(turtle_actionlib_BUILDTOOL_DEPENDS "catkin")
set(turtle_actionlib_BUILDTOOL_EXPORT_DEPENDS )
set(turtle_actionlib_EXEC_DEPENDS "actionlib" "actionlib_msgs" "angles" "message_runtime" "rosconsole" "roscpp" "std_msgs" "turtlesim" "geometry_msgs")
set(turtle_actionlib_RUN_DEPENDS "actionlib" "actionlib_msgs" "angles" "message_runtime" "rosconsole" "roscpp" "std_msgs" "turtlesim" "geometry_msgs")
set(turtle_actionlib_TEST_DEPENDS )
set(turtle_actionlib_DOC_DEPENDS )
set(turtle_actionlib_DEPRECATED "")