set(_CATKIN_CURRENT_PACKAGE "mk")
set(mk_VERSION "1.12.7")
set(mk_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(mk_PACKAGE_FORMAT "1")
set(mk_BUILD_DEPENDS )
set(mk_BUILD_EXPORT_DEPENDS "rosbuild")
set(mk_BUILDTOOL_DEPENDS "catkin")
set(mk_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.69")
set(mk_BUILDTOOL_EXPORT_DEPENDS )
set(mk_EXEC_DEPENDS "rosbuild")
set(mk_RUN_DEPENDS "rosbuild")
set(mk_TEST_DEPENDS )
set(mk_DOC_DEPENDS )
set(mk_DEPRECATED "")