set(_CATKIN_CURRENT_PACKAGE "desktop")
set(desktop_VERSION "1.2.0")
set(desktop_MAINTAINER "Dirk Thomas <dthomas@osrfoundation.org>")
set(desktop_PACKAGE_FORMAT "1")
set(desktop_BUILD_DEPENDS )
set(desktop_BUILD_EXPORT_DEPENDS "robot" "viz" "common_tutorials" "geometry_tutorials" "ros_tutorials" "roslint" "rqt_common_plugins" "rqt_robot_plugins" "urdf_tutorial" "visualization_tutorials")
set(desktop_BUILDTOOL_DEPENDS "catkin")
set(desktop_BUILDTOOL_EXPORT_DEPENDS )
set(desktop_EXEC_DEPENDS "robot" "viz" "common_tutorials" "geometry_tutorials" "ros_tutorials" "roslint" "rqt_common_plugins" "rqt_robot_plugins" "urdf_tutorial" "visualization_tutorials")
set(desktop_RUN_DEPENDS "robot" "viz" "common_tutorials" "geometry_tutorials" "ros_tutorials" "roslint" "rqt_common_plugins" "rqt_robot_plugins" "urdf_tutorial" "visualization_tutorials")
set(desktop_TEST_DEPENDS )
set(desktop_DOC_DEPENDS )
set(desktop_DEPRECATED "")